Table Interface
kysect/SeaInk pull request #18
Opened 2021-04-05 17:04 UTC by ronimizy

2021-04-05 17:29 UTC, annchous requested changes
Это пока не всё, чуть позже досмотрю и добавлю ещё что-нибудь (если найду что)

2021-04-05 17:29 UTC, annchous commented on Source/SeaInk.Core/Entities/UniversitySystemUser.cs
> +        public string FullName => FirstName + MidName + LastName;
Пробелы не нужны? И ещё пусть в формате ФИО это будет)

2021-04-05 17:29 UTC, annchous commented on Source/SeaInk.Core/Models/Tables/IStyles.cs
> +    {
А зачем тебе для этого интерфейс? Можно ведь было просто создать папочку с енамами и накидать туда отдельных енамов прямо файликами LineStyle.cs и тд

2021-04-05 17:29 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/ITable.cs
> +        public int RowCount(TableIndex sheet);
указывать модификатор доступа в интерфейсе тут излишне, по умолчанию в интерфейсе всё и так public

2021-04-05 17:32 UTC, hrrrrustic commented
> Это пока не всё, чуть позже досмотрю и добавлю ещё что-нибудь (если найду что)

Надеюсь после законченного тестового задания?

2021-04-05 17:35 UTC, annchous commented
> > Это пока не всё, чуть позже досмотрю и добавлю ещё что-нибудь (если найду что)
> 
> Надеюсь после законченного тестового задания?

@hrrrrustic возможно.

2021-04-05 17:35 UTC, hrrrrustic commented
> > > Это пока не всё, чуть позже досмотрю и добавлю ещё что-нибудь (если найду что)
> > 
> > 
> > Надеюсь после законченного тестового задания?
> 
> @hrrrrustic возможно.

Да иди делай уже господи

2021-04-05 17:42 UTC, ronimizy commented
> > > > Это пока не всё, чуть позже досмотрю и добавлю ещё что-нибудь (если найду что)
> 
> > > 
> 
> > > 
> 
> > > Надеюсь после законченного тестового задания?
> 
> > 
> 
> > @hrrrrustic возможно.
> 
> 
> 
> Да иди делай уже господи

Открыли блин репозиторий))

2021-04-05 17:59 UTC, hrrrrustic commented
> > > > > Это пока не всё, чуть позже досмотрю и добавлю ещё что-нибудь (если найду что)
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Надеюсь после законченного тестового задания?
> > 
> > 
> > > 
> > 
> > 
> > > @hrrrrustic возможно.
> > 
> > 
> > Да иди делай уже господи
> 
> Открыли блин репозиторий))

Да я так, просто человеку напомнил о дедлайнах

2021-04-05 18:02 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/Entities/Tables/ITable.cs
> +        public List<string> GetValuesForCellsAt(TableIndex index, int count, Direction direction);
Если сделал шаблон для одной ячейки, почему бы не оставить шаблон для нескольких ячеек? Я про <T>

2021-04-05 18:05 UTC, ronimizy commented on Source/SeaInk.Core/Entities/Tables/ITable.cs
> +        public List<string> GetValuesForCellsAt(TableIndex index, int count, Direction direction);
> Если сделал шаблон для одной ячейки, почему бы не оставить шаблон для нескольких ячеек? Я про

Что?

2021-04-05 18:05 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/Models/Tables/BorderStyle.cs
> +        public LineStyle Trailing { get; set; } = new();
Что ты подразумеваешь по Leading и Trailing?

2021-04-05 18:06 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/Models/Tables/BorderStyle.cs
> +
Хм?

2021-04-05 18:07 UTC, hrrrrustic commented on Source/SeaInk.Core/Models/Tables/BorderStyle.cs
> +        public LineStyle Trailing { get; set; } = new();
Это устоявшиеся названия отступов/пробелов/пустых строк в начале и конце

2021-04-05 18:12 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/Models/Tables/TableIndex.cs
> +        }
Может быть сделаем Sheet тоже int? Просто у меня в excel доступ по чиселке, а не по строке к листу. В гугле обязательно по имени листа?

2021-04-05 18:13 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/Services/TableSyncService.cs
> +            SaveWorkbook(path);
Не знаю какой идиот это писал всё

2021-04-05 18:15 UTC, ronimizy commented on Source/SeaInk.Core/Models/Tables/BorderStyle.cs
> +        public LineStyle Trailing { get; set; } = new();
Leading - левый, Trailing - правый, термины из вёрстки

2021-04-05 18:17 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/Entities/Tables/ITable.cs
> +        public List<string> GetValuesForCellsAt(TableIndex index, int count, Direction direction);
А, осознал. Хз насколько тут нужен отдельный метод с List<string>, если можно будет итак указывать тип данные string. Но хотя, ладно, наверно так будет удобней

2021-04-05 18:22 UTC, ronimizy commented on Source/SeaInk.Core/Entities/Tables/ITable.cs
> +        public List<string> GetValuesForCellsAt(TableIndex index, int count, Direction direction);
Чаще всего придется юзать ```string```, так что женерики будут появляться только при необходимости - конечный код будет чище

2021-04-05 18:23 UTC, ronimizy commented on Source/SeaInk.Core/Models/Tables/BorderStyle.cs
> +
При переопределении конструктора нужно переопределять пустой, иначе - ошибка

2021-04-05 18:24 UTC, ronimizy commented on Source/SeaInk.Core/Services/TableSyncService.cs
> +            SaveWorkbook(path);
Всё равно под интерфейс и Entity Service переписывать)

2021-04-05 18:32 UTC, ronimizy commented on Source/SeaInk.Core/Models/Tables/TableIndex.cs
> +        }
Можно

2021-04-05 18:32 UTC, ronimizy commented on Source/SeaInk.Core/Models/Tables/IStyles.cs
> +    {
Разобью

2021-04-05 18:42 UTC, ronimizy commented on Source/SeaInk.Core/Models/Tables/BorderStyle.cs
> +            Top = new LineStyle(Color.Black, bottom);
Хы

2021-04-05 18:48 UTC, ronimizy commented on Source/SeaInk.Core/Entities/Tables/ITable.cs
> +        public int RowCount(TableIndex sheet);
А это остаток от попыток внедрения абстрактного класса)

2021-04-05 20:48 UTC, FrediKats requested changes
Местами кажется, что тут прям слишком много абстракций над экселем. По факту свою либу почти написали поверх либы)

2021-04-05 20:48 UTC, FrediKats commented on Source/SeaInk.Core/Entities/Subject.cs
> +        public Subject(int id, string title, DateTime startDate, DateTime endDate, List<StudyAssignment>? assignments = null)
? тут не обязательный. Это уже упоротые штуки из нулабилити.

2021-04-05 20:48 UTC, FrediKats commented on Source/SeaInk.Core/Entities/Tables/ITable.cs
> +         * }
А в чем смысл таких трай кетчей? Мы же по факту теряем информацию о том, что случилось и где случилось. + вызывающий код не будет знать чо что-то упало.

2021-04-05 20:48 UTC, FrediKats commented on Source/SeaInk.Core/Entities/Tables/ITable.cs
> +            Vertical
Не стоит делать вложенные в интерфейсы типы.

2021-04-05 20:59 UTC, ronimizy commented
> Местами кажется, что тут прям слишком много абстракций над экселем. По факту свою либу почти написали поверх либы)

Таков путь

2021-04-05 21:10 UTC, hrrrrustic commented on Source/SeaInk.Core/Entities/Subject.cs
> +        public Subject(int id, string title, DateTime startDate, DateTime endDate, List<StudyAssignment>? assignments = null)
Люди сразу к хорошему привыкают, что ты!

2021-04-06 08:06 UTC, ronimizy commented on Source/SeaInk.Core/Entities/Tables/ITable.cs
> +         * }
Тут трайкеч скорее для иллюстративных целей, показать что метод кидает)

2021-04-06 08:06 UTC, ronimizy commented on Source/SeaInk.Core/Entities/Tables/ITable.cs
> +            Vertical
Вынес

2021-04-06 17:12 UTC, FrediKats requested changes

2021-04-06 17:12 UTC, FrediKats commented on Source/SeaInk.Core/FakeUniversitySystemApi.cs
> +            return list;
У фейкера есть метод, который генерирует набор элементов.

2021-04-06 17:12 UTC, FrediKats commented on Source/SeaInk.Core/FakeUniversitySystemApi.cs
> +            int top = new Random().Next(l, h);
new Random - это не очень хорошо. Стоит почитать почему.

2021-04-06 17:12 UTC, FrediKats commented on Source/SeaInk.Core/Models/Tables/Enums/TextWrapping.cs
> +        Cut //Обрезать текст
Лучше писать через summary коммент.
Напиши "///" и тебе IDE сгенерит. Такие комменты будут подсвечиваться когда ты наводишь на это значение в коде. + Комменты все же лучше на англ, а то кодировка может умереть как минимум.

2021-04-06 17:12 UTC, FrediKats commented on Source/SeaInk.Core/Models/Tables/ICellStyle.cs
> +        public FontStyle FontStyle { get; set; }
Не убрал паблики.

2021-04-06 17:12 UTC, FrediKats commented on Source/SeaInk.Core/Models/Tables/ISheetMarkup.cs
> +        public List<(TableIndex index, ICellStyle style)> Special { get; set; }
Если и есть какие-то комменты, то через summary и на англ.

2021-04-06 17:58 UTC, ronimizy commented on Source/SeaInk.Core/FakeUniversitySystemApi.cs
> +            int top = new Random().Next(l, h);
Понимаю, часики тикают, но медленно

2021-04-06 18:12 UTC, FrediKats approved these changes

2021-04-06 18:16 UTC, annchous approved these changes

2021-04-06 18:22 UTC, merged