Google Table
kysect/SeaInk pull request #25
Opened 2021-04-15 09:36 UTC by ronimizy

Program.cs включает в себя тест, он создаёт лист, заполняет диапазон значениями двух видов, переименовывает лист, переименовывает таблицу (сейчас она названа так как в коде, так что стоит написать что-нибудь новое если захотите проверить), форматирует диапазон ячеек и одну ячейку, объединяет диапазон ячеек, удаляет столбец и строку.
Сама таблица
https://docs.google.com/spreadsheets/d/1Z7JaEecXh5K6NPwrRuZC0OfM3TMCzHt-_POD2812J_k/edit?usp=sharing

Для теста нужны креды и прописка как тестировщик в гугловском проекте, напишите в диск, всё организую

2021-04-15 17:12 UTC, VitalDikov commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +        }
Слишком большой метод. Надо бы разделить

2021-04-15 17:12 UTC, VitalDikov commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +                                "hyperlink"
вхардкоженная строка без стрингбилдера

2021-04-15 17:15 UTC, VitalDikov commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +        private string SpreadsheetId { get; set; } = "";
String.Empty()

2021-04-15 17:27 UTC, VitalDikov commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +        }
smell

2021-04-15 17:48 UTC, annchous requested changes
Думаем над интерфейсом. + сам класс выглядит очень громоздким

2021-04-15 17:48 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +        private string SpreadsheetId { get; set; } = "";
Некрасиво. Можно оставить null (как по умолчанию) и хендлить потом, где нужно.

2021-04-15 17:48 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +            };
Не прямая ответственность класса гугл таблицы, можно сделать экстеншн методами.

2021-04-15 17:48 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +        public GoogleTable()
Конструктор выше поднять (после полей, до методов).

2021-04-15 17:48 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +                    new()
Используй имя типа. Не через IDE не понятно сразу, что за тип.

2021-04-15 17:48 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +                                ")," +
Выглядит немного дико) 
Можно заменить на StringBuilder и аппендить по логической единице типа borderColor, (...), horizontalAlignment и т.д.

2021-04-15 17:48 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +            return count.Value;
Кажется, можно ограничиться
```suggestion
            return count ?? throw new NonExistingIndexException();
```

2021-04-15 17:51 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +            };
https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/classes-and-structs/extension-methods

2021-04-15 17:59 UTC, Bibletoon commented on Source/SeaInk.Sample/Program.cs
> +            table.Load("1Z7JaEecXh5K6NPwrRuZC0OfM3TMCzHt-_POD2812J_k");
Включать в комит различные приватные ключи не безопасно.

2021-04-15 19:21 UTC, ronimizy commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +            };
+

2021-04-15 20:08 UTC, ronimizy commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +        }
Добавил экстеншены к контейнерам стиля для каста к гугловским, вынес строку с полями, сжалось до ~20 строк

2021-04-15 20:09 UTC, ronimizy commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +                                "hyperlink"
вынес как приватную константу

2021-04-15 20:10 UTC, ronimizy commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +        }
rip

2021-04-15 20:10 UTC, ronimizy commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +        private string SpreadsheetId { get; set; } = "";
оставил по умолчанию

2021-04-15 20:11 UTC, ronimizy commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +        public GoogleTable()
done

2021-04-15 20:12 UTC, ronimizy commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +                    new()
done

2021-04-15 20:13 UTC, ronimizy commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +                                ")," +
Так как каждое обновление переопределяет все поля, вынес её в отдельную константу, чтобы лишний раз не пересобирать

2021-04-15 20:14 UTC, ronimizy commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +            return count.Value;
Не знал что так можно, выглядит красиво

2021-04-15 20:16 UTC, ronimizy commented on Source/SeaInk.Sample/Program.cs
> +            table.Load("1Z7JaEecXh5K6NPwrRuZC0OfM3TMCzHt-_POD2812J_k");
Это не ключ, а id public Гугл таблицы

2021-04-15 21:42 UTC, annchous requested changes

2021-04-15 21:42 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +            }
Теперь можно делать так, тогда не будет замусоривания типа `UserCredential credential;`
```suggestion
            using var stream = new FileStream("credentials.json", FileMode.Open, FileAccess.Read);
            const string credPath = "token.json";
            var credential = GoogleWebAuthorizationBroker.AuthorizeAsync(
                GoogleClientSecrets.Load(stream).Secrets,
                Scopes,
                "user",
                CancellationToken.None,
                new FileDataStore(credPath, true)).Result;
            Console.WriteLine("Credential file saved to: " + credPath);
            
            Service = new SheetsService(new BaseClientService.Initializer
            {
                HttpClientInitializer = credential,
                ApplicationName = ApplicationName,
            });
```

2021-04-15 21:42 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +                Console.WriteLine("Credential file saved to: " + credPath);
Не очень нравится `Console.WriteLine` в таком месте в коде)
Может это можно и выпилить, но могу предложить сделать логер в качестве замены. Можно свой простенький в виде какого-то [синглтона](https://refactoring.guru/ru/design-patterns/singleton/csharp/example), пишет пусть тоже пока в консоль. Опережая вопрос по расположению класса: можно создать папочку `Utils` в корне проекта `.Core`.

2021-04-15 21:42 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +            });
```suggestion
            SetValuesForCellsAt(index, new List<List<T>>
            {
                new List<T> { value }
            });
```

2021-04-15 21:42 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +                    .WithColumn(index.Column + values.Select(v => v.Count).Max() - 1));
Я вижу, что хотелось выдержать единый стиль, но чуть компактнее тоже хочется)
```suggestion
            var range = new TableIndexRange(index, index
                    .WithRow(index.Row + values.Count - 1)
                    .WithColumn(index.Column + values.Select(v => v.Count).Max() - 1));
```

2021-04-15 21:42 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +                range.ToString());
Вроде видно, что это и реквест (из названия) и что метод, который его выдаёт называется Update. Скоратим)
```suggestion
            var request = Service.Spreadsheets.Values.Update(body, SpreadsheetId, range.ToString());
```

2021-04-15 21:42 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +                SpreadsheetsResource.ValuesResource.UpdateRequest.ValueInputOptionEnum.USERENTERED;
В принципе, тоже можно было бы сократить, но оставим так.

2021-04-15 21:42 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +                    Fields = "title"
Повторяется строка, предлагаю законстантить для удобства

2021-04-15 21:42 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +                    ShiftDimension = "ROWS"
Можно законстантить, повторяется. Что-то типа `RowsDimension`

2021-04-15 21:42 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +                    ShiftDimension = "COLUMNS"
Пусть тоже будет константой

2021-04-16 19:21 UTC, annchous approved these changes

2021-04-16 19:40 UTC, merged