feature: add some HttpGet methods
kysect/SeaInk pull request #26
Opened 2021-04-17 12:27 UTC by MGSDS

add GetSubjectsByMentorId method
add GetgroupsByMentorIdAndSubject method
close #19

2021-04-17 12:34 UTC, I-SER-I commented on Source/SeaInk.Endpoints/Server/Controllers/UniversityApiController.cs
> +                select division.Groups;
Переписать на нормальные линки (LINQ Extension)

2021-04-17 12:34 UTC, I-SER-I commented on Source/SeaInk.Endpoints/Server/Controllers/UniversityApiController.cs
> +                select division.Subject;
Переписать на нормальные линки (LINQ Extension)

2021-04-17 12:47 UTC, I-SER-I commented on Source/SeaInk.Endpoints/Server/Controllers/UniversityApiController.cs
> +            IEnumerable<List<StudyGroup>> groupsQuery =
Не нужно упароваться строгой типизацией, всегда есть `var`

2021-04-17 13:11 UTC, I-SER-I commented on Source/SeaInk.Endpoints/Server/Controllers/UniversityApiController.cs
> +            });
Выглядит страшло, немного переборщил)

2021-04-17 13:29 UTC, I-SER-I commented on Source/SeaInk.Endpoints/Server/Controllers/UniversityApiController.cs
> +        public List<Subject> GetSubjectsByMentorId(Int32 id)
Поменять CLR инты на обчные

2021-04-17 13:30 UTC, I-SER-I commented on Source/SeaInk.Endpoints/Server/Controllers/UniversityApiController.cs
> +        public List<StudyGroup> GetgroupsByMentorIdAndSubject(Int32 mid, Int32 sid)
[Аналогично](https://github.com/kysect/SeaInk/pull/26/commits/c221b268ba27681e5407922906295f024f460498#r615255643)

2021-04-17 13:42 UTC, I-SER-I commented on Source/SeaInk.Endpoints/Server/Controllers/UniversityApiController.cs
> +            });
Лучше как-то так
```suggestion
return mentorDivisions
                .Where(division => division.Subject.Id == sid)
                .SelectMany(division => division.Groups)
                .DistinctBy(group => group.SystemId)
                .ToList();
```

2021-04-17 13:50 UTC, I-SER-I commented on Source/SeaInk.Endpoints/Server/Controllers/UniversityApiController.cs
>          public List<StudyGroup> GetgroupsByMentorIdAndSubject(int mid, int sid)
Странный нейминг, призываю @annchous

2021-04-17 13:56 UTC, I-SER-I commented on Source/SeaInk.Endpoints/Server/Controllers/UniversityApiController.cs
> +            return mentorDivisions.Select( x => x.Subject).ToList();
Пробел)

2021-04-17 22:38 UTC, annchous requested changes

2021-04-17 22:38 UTC, annchous commented on Source/SeaInk.Endpoints/Server/Controllers/UniversityApiController.cs
> +        [HttpGet("mentor/{mentorId}/subjects")]
```suggestion
        [HttpGet("mentors/{mentorId}/subjects")]
```

2021-04-17 22:38 UTC, annchous commented on Source/SeaInk.Endpoints/Server/Controllers/UniversityApiController.cs
> +        [HttpGet("mentor/{mentorId}/subject/{subjectId}/groups")]
```suggestion
        [HttpGet("mentors/{mentorId}/subjects/{subjectId}/groups")]
```

2021-04-18 07:24 UTC, I-SER-I reviewed
Ну вроде норм

2021-04-18 08:35 UTC, annchous approved these changes

2021-04-18 08:41 UTC, merged