Google Drive Creation
kysect/SeaInk pull request #28
Opened 2021-04-21 08:26 UTC by ronimizy

close #5

2021-04-21 19:12 UTC, annchous requested changes
Пока что фиксим это

2021-04-21 19:12 UTC, annchous commented on Source/SeaInk.Core/Models/Tables/SheetIndex.cs
> +        }
Выглядит не очень, попробуй так
```suggestion
        public override bool Equals(object obj)
        {
            var sheetIndex = obj as SheetIndex;
            if (sheetIndex == null)
            {
                return false;
            }
            
            return SheetName == sheetIndex.SheetName && SheetId == sheetIndex.SheetId;
        }
```

2021-04-21 19:12 UTC, annchous commented on Source/SeaInk.Core/Models/Tables/Styles/EmptyCellStyle.cs
> +    public class EmptyCellStyle : ICellStyle
Может DefaultCellStyle?

2021-04-21 19:22 UTC, ronimizy commented on Source/SeaInk.Core/Models/Tables/Styles/EmptyCellStyle.cs
> +    public class EmptyCellStyle : ICellStyle
Такой уже есть, могу предложить  ```PlainCellStyle```

2021-04-21 19:32 UTC, ronimizy commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +                        if (location != null)
Да, например, самая первая итерация, первая папка в пути не существует, location не поменяется и будет null

2021-04-21 19:33 UTC, ronimizy commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +            }
done

2021-04-21 19:34 UTC, ronimizy commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +            }
Эксепшн здесь не нужен, пустой путь означает сохранение в корень диска

2021-04-21 19:34 UTC, ronimizy commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +                    List<string> folders = searchRequest.Execute().Files
done

2021-04-21 19:35 UTC, ronimizy commented on Source/SeaInk.Core/Models/Tables/SheetIndex.cs
> +        }
done

2021-04-21 19:38 UTC, annchous commented on Source/SeaInk.Core/Models/Tables/Styles/EmptyCellStyle.cs
> +    public class EmptyCellStyle : ICellStyle
а зачем этот?

2021-04-21 19:39 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +                        if (location != null)
А, да, окей, я забыла. что там цикл сверху ещё)

2021-04-21 19:41 UTC, ronimizy commented on Source/SeaInk.Core/Models/Tables/Styles/EmptyCellStyle.cs
> +    public class EmptyCellStyle : ICellStyle
Хм, похоже он затесался вместе с наработками отменённого table-context, которые я переносил в эту ветку. В принципе можно его убрать.

2021-04-22 19:45 UTC, ronimizy commented on Source/SeaInk.Core/Models/Tables/Styles/EmptyCellStyle.cs
> +    public class EmptyCellStyle : ICellStyle
deleted

2021-04-23 12:41 UTC, hrrrrustic commented on Source/SeaInk.Core/Models/Tables/SheetIndex.cs
> +        }
@annchous Лол, что за странное мувы?
1) Ты зачем удалила типизированный Equals?
2) Ну новый метод брух, чо так много строк
```C#
public override bool Equals(object obj)
        {
            return obj is SheetIndex sheet && Equals(sheet);
        }
```
ииии...это все!

2021-04-23 12:45 UTC, hrrrrustic commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +            }
@annchous Ну, инверт конечно по фактам. Но как бы причина-то осталась на месте:
https://github.com/kysect/SeaInk/blob/2f4e7d7ed5ee16dbcf26be6160847efaf7188301/Source/SeaInk.Core/Entities/Tables/GoogleTable.cs#L118-L123

За = null надо банить сразу. Хочется сделать необязательный аргумент - делай отдельную перегрузку
```C#
public string Create(TableInfo tableInfo) => Create(tableInfo, Array.Empty<string>())
```
Не надо ради бога коллекции null'ами делать

2021-04-23 13:02 UTC, annchous commented on Source/SeaInk.Core/Models/Tables/SheetIndex.cs
> +        }
@hrrrrustic спасибо, учитель

2021-04-23 17:35 UTC, hrrrrustic requested changes

2021-04-23 17:35 UTC, hrrrrustic commented on Source/SeaInk.Core/Entities/Division.cs
>          }
1. А почему ```TableInfo = null```?
2. Раз уж ты пишешь пачку конструкторов с разным кол-вом аргументов, то пусть они уж тогда друг друга вызывают:
```C#
public Division() : this(new Subject(), new List<StudyGroup>(), null)
        {}
```
3. Да и в целом какой-то странный конструктор, может проще сделать его приватным и запертить создавать без аргументов?

2021-04-23 17:35 UTC, hrrrrustic commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +        public string Create(TableInfo tableInfo, List<string> path = null)
Ну про это уже писал

2021-04-23 17:35 UTC, hrrrrustic commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
>              request.ValueInputOption = USERENTERED;
Господи что это? О.о

2021-04-23 17:35 UTC, hrrrrustic commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +        private string EstablishLocationForPath(IReadOnlyCollection<string> path)
Лайк за ридонликоллекшн

2021-04-23 17:35 UTC, hrrrrustic commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +                searchRequest.Q = @"mimeType='application/vnd.google-apps.folder'";
Вынеси хотя бы такие строки в константы этого же класса. Задолбаешься же потом скроллить код, если вдруг поменять надо будет

2021-04-23 17:35 UTC, hrrrrustic commented on Source/SeaInk.Core/Models/Google/Exceptions/InsufficientPermissionException.cs
> +            : this("") { }
Не понял, что тут происходит?

2021-04-23 17:35 UTC, hrrrrustic commented on Source/SeaInk.Core/Models/Tables/SheetIndex.cs
> +        protected bool Equals(SheetIndex other)
А почему ```protected```?

2021-04-23 17:35 UTC, hrrrrustic commented on Source/SeaInk.Core/Models/Tables/SheetIndex.cs
> +            return HashCode.Combine(SheetName, SheetId);
Уверен, что нужно комбайнить? Id звучит как нормальный хешкод сам по себе

2021-04-23 17:35 UTC, hrrrrustic commented on Source/SeaInk.Core/Models/Tables/TableIndex.cs
> +
А...зачем?

2021-04-23 17:35 UTC, hrrrrustic commented on Source/SeaInk.Core/Models/Tables/TableIndex.cs
> +
кекв ну все, request changes, помянем

2021-04-23 17:35 UTC, hrrrrustic commented on Source/SeaInk.Core/Services/AuthService.cs
> +    public static class AuthService
аче в смысле с чего вдруг тут статик

2021-04-23 17:35 UTC, hrrrrustic commented on Source/SeaInk.Core/Services/AuthService.cs
> +            return true;
Да и так нормально, сами разберутся если че, хрен ли они пользуются, если доступа нет

2021-04-23 18:08 UTC, ronimizy commented on Source/SeaInk.Core/Entities/Division.cs
>          }
Пустой конструктор нужен для фейкера данных

2021-04-23 18:10 UTC, ronimizy commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +        public string Create(TableInfo tableInfo, List<string> path = null)
А что здесь не так? Если путь пустой, то файл создаётся в корне диска

2021-04-23 18:16 UTC, ronimizy commented on Source/SeaInk.Core/Models/Google/Exceptions/InsufficientPermissionException.cs
> +            : this("") { }
А конкретнее?)

2021-04-23 18:17 UTC, ronimizy commented on Source/SeaInk.Core/Models/Tables/SheetIndex.cs
> +        protected bool Equals(SheetIndex other)
Так сказал Rider

2021-04-23 18:37 UTC, hrrrrustic commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +        public string Create(TableInfo tableInfo, List<string> path = null)
Ну, это здорово! А почему null, а не пустой лист?

2021-04-23 18:38 UTC, hrrrrustic commented on Source/SeaInk.Core/Entities/Division.cs
>          }
Не вижу связи конечно, но ок

2021-04-23 18:39 UTC, hrrrrustic commented on Source/SeaInk.Core/Models/Google/Exceptions/InsufficientPermissionException.cs
> +            : this("") { }
Ну, у тебя аргумент ```string message```, но в итоге ты форсишь свое сообщение. А в конструкторе без аргументов наоборот ничего не форсишь

2021-04-23 18:39 UTC, hrrrrustic commented on Source/SeaInk.Core/Models/Tables/SheetIndex.cs
> +        protected bool Equals(SheetIndex other)
bruh

2021-04-23 19:04 UTC, ronimizy commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +        public string Create(TableInfo tableInfo, List<string> path = null)
<img width="860" alt="Снимок экрана 2021-04-23 в 22 04 16" src="https://user-images.githubusercontent.com/71693183/115918169-dbc73700-a47f-11eb-86d9-149742573a3b.png">
 Rider не даёт!

2021-04-23 19:21 UTC, hrrrrustic commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +        public string Create(TableInfo tableInfo, List<string> path = null)
Потому что через = аргументам можно только константы присваивать. Тебе придется написать еще один метод с другими аргументами, который будет вызывать этот:
```C#
public string Create(TableInfo tableInfo) => Create(tableInfo, new List<string>())
```

А вот этом просто оставить ```List<string> path```

2021-04-23 20:15 UTC, ronimizy commented on Source/SeaInk.Core/Models/Tables/TableIndex.cs
> +
fixed

2021-04-23 20:15 UTC, ronimizy commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
>                  new FileDataStore(credPath, true)).Result;
fixed

2021-04-23 20:23 UTC, ronimizy commented on Source/SeaInk.Core/Models/Tables/SheetIndex.cs
> +        protected bool Equals(SheetIndex other)
kk

2021-04-23 20:38 UTC, ronimizy commented on Source/SeaInk.Core/Services/AuthService.cs
> +    public static class AuthService
umbral

2021-04-26 20:51 UTC, ronimizy commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +        public string Create(TableInfo tableInfo, List<string> path = null)
done

2021-04-27 07:30 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/Models/Tables/SheetIndex.cs
> +        public int Id { get; set; }
У тебя используется где-то SheetId? Просто, если что, у меня ни разу не пригодилось. Если и тебе он не нужен, то проще удалить это.

2021-04-27 10:43 UTC, ronimizy commented on Source/SeaInk.Core/Models/Tables/SheetIndex.cs
> +        public int Id { get; set; }
Нужен, для запросов гуглу

2021-04-27 19:44 UTC, annchous requested changes

2021-04-27 19:44 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +                    .Where(f => f.Name == folder && !f.Trashed.Value)
![image](https://user-images.githubusercontent.com/57408376/116301034-40e49a80-a7a8-11eb-82e5-af750e1e7041.png)
неприятненько

2021-04-27 19:44 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +                    }
```suggestion

                    if (location != null)
                    {
                        folderFile.Parents = new List<string> {location};
                    }
```

2021-04-27 19:44 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +
```suggestion

```

2021-04-27 19:44 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +
```suggestion

```

2021-04-27 19:44 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +            return location;
Опиши мне ещё раз, пожалуйста, что делает этот метод

2021-04-27 19:48 UTC, ronimizy commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +                    .Where(f => f.Name == folder && !f.Trashed.Value)
Ну, оно конечно "может" кинуть эксепшн, но так как я запрашиваю это поле, оно должно присутствовать

2021-04-28 08:33 UTC, ronimizy commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +                    .Where(f => f.Name == folder && !f.Trashed.Value)
done

2021-04-28 09:46 UTC, FrediKats requested changes

2021-04-28 09:46 UTC, FrediKats commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +        private string EstablishLocationForPath(IEnumerable<string> path)
Это CreateFolder, который умеет создавать Subfolders? Может тогда просто CreateFolder и назвать?

2021-04-28 09:46 UTC, FrediKats commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +        private string EstablishLocationForPath(IEnumerable<string> path)
IEnumerable<string> path в твоем случае это не рандомные строки, а специфичный путь на гугл-диске, который задаешь ты списком названий директорий. Выдели это в сущность GoogleTablePath

2021-04-28 09:46 UTC, FrediKats commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +            string location = null;
location = ParentFolder?

2021-04-28 09:46 UTC, FrediKats commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +                    .Select(f => f.Id)
SingleOrDefault

2021-04-28 09:46 UTC, FrediKats commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +                }
Вынеси это с метод GetFolder, который будет принимать ParentFolder и FolderName

2021-04-28 09:49 UTC, ronimizy commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +            string location = null;
≠, путь должен прописываться от корня, можно конечно от какого-то конкретного айпишника идти, но откуда ему появится

2021-04-28 09:53 UTC, hrrrrustic commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +                    }
Окно открой

2021-04-28 10:05 UTC, ronimizy commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +                    .Select(f => f.Id)
done

2021-04-28 10:05 UTC, ronimizy commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +                }
done

2021-04-28 10:07 UTC, ronimizy commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +        private string EstablishLocationForPath(IEnumerable<string> path)
не совсем

2021-04-28 13:50 UTC, ronimizy commented on Source/SeaInk.Core/Entities/Tables/GoogleTable.cs
> +        private string EstablishLocationForPath(IEnumerable<string> path)
done

2021-04-28 13:52 UTC, ronimizy commented
@FrediKats мерге?

2021-04-28 14:09 UTC, FrediKats approved these changes

2021-04-28 14:09 UTC, merged