feat: Implementation of ITable
kysect/SeaInk pull request #29
Opened 2021-04-25 16:07 UTC by Ar4eR-ValerA

Многострадальная имплементация интерфейса. По договорённости имплементация кастомизации таблицы отсутствует, так как Эксель нужен для дебага, поэтому изменения цветов и прочего тут не нужно, также по договорённости количество столбцов и строчек тоже не подсчитывается за ненадобностью.

2021-04-25 17:35 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +        private XLWorkbook _workbook = null!;
А для чего потребовалось `= null!`?

2021-04-25 20:33 UTC, annchous requested changes

2021-04-25 20:33 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +        }
Создание таблицы выглядит довольно странно, т.к. таблица не сохраняется сразу после создания в файл, то есть `Create` - довольно символический нейминг
```suggestion
        public string Create(string path)
        {
            _pathToFile = path;

            _workbook = new XLWorkbook();
            _workbook.AddWorksheet("Sheet1");
            _workbook.SaveAs(path);

            return path;
        }
```

2021-04-25 20:33 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +            _workbook.SaveAs(_pathToFile);
Я проверила, что `SaveAs` из коробки сам перезаписывает существующий файл новым
```suggestion
            _workbook.SaveAs(_pathToFile);
```

2021-04-25 20:33 UTC, annchous commented on Source/SeaInk.Sample/Program.cs
> +            table.Create(@"E:\Desktop\Test.xlsx");
Упадёт у меня. Делай через [специальные методы](https://docs.microsoft.com/ru-ru/dotnet/api/system.environment.getfolderpath?view=net-5.0)

2021-04-25 20:33 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +        private string _pathToFile;
Это можно обозвать более лаконичным `_filePath`

2021-04-25 20:33 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +        }
Пыталась предложить более аккуратное решение, даю слово @hrrrrustic 
```suggestion
        public void Rename(string name)
        {
            var fileInfo = new FileInfo(_pathToFile);
            var newPath = Path.Combine(Path.GetDirectoryName(_pathToFile)!, name);
            _pathToFile = newPath;

            fileInfo.MoveTo(newPath);
        }
```

2021-04-25 20:33 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +        public void Load(string address)
Можешь себе позволить
```suggestion
        public void Load(string path)
```

2021-04-25 20:33 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +            Save();
Сохранение в файл. Ты уверен, что оно нужно сразу после загрузки?

2021-04-25 20:33 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +        }
Много странных телодвижений для удаления листа. Из коробки оно умеет в
```csharp
_workbook.Worksheet(sheet.SheetName).Delete();
```
И не уверена, что надо тут же сохранять.

2021-04-25 20:51 UTC, hrrrrustic commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +        }
Хз не шарю в апи для работы с фс

2021-04-25 20:56 UTC, hrrrrustic commented on Source/SeaInk.Core/Entities/Subject.cs
> +        public Subject(int id, string title, DateTime startDate, DateTime endDate, List<StudyAssignment>? assignments = null)
@annchous

2021-04-25 20:59 UTC, annchous commented on Source/SeaInk.Core/Entities/Subject.cs
> +        public Subject(int id, string title, DateTime startDate, DateTime endDate, List<StudyAssignment>? assignments = null)
https://github.com/kysect/SeaInk/pull/28/files#r619447659

2021-04-26 07:51 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/Entities/Mentor.cs
> +        public List<Division> Divisions { get; set; } = new List<Division>();
Это не из мастера вроде, а из Гошиной ветки, потом замерджитсся. Я изменил для себя тут, так как у меня не компилится версия Гоши, которая в мастере лежит)

2021-04-26 07:54 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +        }
Не предполагал, что такое есть) Окей, спасибо

2021-04-26 08:03 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +        }
Я не хотел выкидывать тут NotImplementedException, так как в теории, для простоты дебага, в идеале брать код для работы с таблицей Google, менять Google на Excel и сразу запускать. Методы Форматирования сработают, но ничего не сделают. А если вставить исключения, то прога будет падать, а значит в коде придётся копаться и удалять все неимплементированные методы из кода

2021-04-26 08:40 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +        }
Я свой и твой способ скомбинирую, ибо saveAs в библиотеке очень криво работает и ему оч не нравится, moveTo ...

2021-04-26 08:44 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +        }
Да..... Из коробки он вроде бы умеет. Но почему-то при следующей попытке сохранения файла падает. Это оч странная фигня, могу когда-нибудь в дискорде в демонстрации экрана показать, может будут идеи с тем, почему это так и как это исправить.
* Если удалить лист из файла и сохранить сразу файл(С тем же именем), то программа падает. 
* А если удалить лист, сохранить это в другой файл(С другим именем), удалить исходный файл, а потом переименовать новый в исходный, то всё работает.

2021-04-26 08:45 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +        }
И сохранять думаю нужно сразу, так как это изменения в таблице. Нужно их сохранить.

2021-04-26 09:07 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +        }
Тогда обсудим в дискорде этот момент

2021-04-27 13:48 UTC, Ar4eR-ValerA commented
@annchous 
@FrediKats 
Мерджим?

2021-04-27 13:53 UTC, hrrrrustic commented
А меня даже не пинганул...

2021-04-27 13:57 UTC, hrrrrustic commented on Source/SeaInk.Sample/Program.cs
> +            var path = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
Ля крутой, аж SpecialFolder нагуглил, уважаю

2021-04-27 14:04 UTC, annchous commented on Source/SeaInk.Sample/Program.cs
> +            var path = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
я научила!

2021-04-27 14:05 UTC, hrrrrustic commented on Source/SeaInk.Sample/Program.cs
> +            var path = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
А ты-то как до этого дожила? О.о

2021-04-27 14:20 UTC, annchous commented on Source/SeaInk.Sample/Program.cs
> +            var path = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
жизнь заставила писать лабу по бекапам

2021-04-27 14:21 UTC, hrrrrustic commented on Source/SeaInk.Sample/Program.cs
> +            var path = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
кекв

2021-04-27 14:21 UTC, hrrrrustic commented on Source/SeaInk.Sample/Program.cs
> +            var path = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
а когда жизнь заставит начать писать JustResharper?

2021-04-27 14:52 UTC, annchous commented on Source/SeaInk.Sample/Program.cs
> +            var path = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
поживём увидим

2021-04-27 14:53 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +                    var newIndex = new TableIndex(index.SheetName, index.SheetId, index.Column + column + 1, index.Row +row + 1);
```suggestion
                    var newIndex = new TableIndex(index.SheetName, index.SheetId, index.Column + column + 1, index.Row + row + 1);
```

2021-04-27 14:53 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +
```suggestion

```

2021-04-27 14:53 UTC, annchous commented on Source/SeaInk.Sample/Program.cs
> +    public static class Program
зачем?

2021-04-27 14:55 UTC, Ar4eR-ValerA commented on Source/SeaInk.Sample/Program.cs
> +    public static class Program
Когда с alt enter пробегался по проге видимо предложило так сделать, я не задумывался особо) Исправлю обратно

2021-04-27 14:55 UTC, hrrrrustic commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +                    var newIndex = new TableIndex(index.SheetName, index.SheetId, index.Column + column + 1, index.Row +row + 1);
душ

2021-04-27 14:55 UTC, hrrrrustic commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +
нила

2021-04-27 19:01 UTC, annchous commented
@Ar4eR-ValerA Этого не должно тут быть https://github.com/kysect/SeaInk/blob/1e4b73d0aca54b85538c00a1a75b140e160a9c11/Source/SeaInk.Core/Services/TableSyncService.cs#L180

2021-04-27 19:07 UTC, Ar4eR-ValerA commented
https://github.com/kysect/SeaInk/pull/29#issuecomment-827843736
@annchous 
Ты откуда взяла этот коммит?) Я этот файл удалил полностью вроде, этого всего нет уже. Если файл не удалился, то нужно его в ветке удалить, но я посмотрел, файла этого там уже нет

2021-04-27 19:11 UTC, annchous commented
> Ты откуда взяла этот коммит?) Я этот файл удалил полностью вроде, этого всего нет уже. Если файл не удалился, то нужно его в ветке удалить, но я посмотрел, файла этого там уже нет

@Ar4eR-ValerA А, my fault. Я увидела это и не обратила внимания, что нахожусь в Гошиной ветке)

2021-04-28 07:32 UTC, FrediKats requested changes

2021-04-28 07:32 UTC, FrediKats commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +            _workbook.AddWorksheet("Important Sheet");
Я бы вынес в константное поле и подписал, что это дефолтный темплейт + добивал коммент, что без него сейв падает.

2021-04-28 07:32 UTC, FrediKats commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +            var newPath = Path.Combine(Path.GetDirectoryName(_filePath)!, name);
Да господи, отключите вы это чекер и не ставьте !, оно же не работает если нормально не настроить)

2021-04-28 07:32 UTC, FrediKats commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +            File.Delete(oldPath);
А файл нельзя просто переименовать без сейва в новый путь и удаления старого?

2021-04-28 07:32 UTC, FrediKats commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +            return (T) _workbook.Worksheet(index.SheetName).Cell(index.Row, index.Column).Value;
А если значение null, оно не упадет на касте? Было бы неплохо, если бы при null значнеии там null и вернулся. Я бы завел таску на рефакторинг отдельно на этот ресерч, возможно при кастах к int'ам стоит возвращать не int , а int?

2021-04-28 07:32 UTC, FrediKats commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +            }
Ну блин, это как-то костыльно) Если нужно иттерироваться по отдельно взятым строкам, то давайте в range сделаем еще один метод иттерирования, но уже по строкам, а не ячейкам. Можно тоже записать отдельной таской на рефакторинг.

2021-04-28 07:32 UTC, FrediKats commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +            _workbook.Worksheet(index.SheetName).Cell(index.Row, index.Column).Value = value!.ToString();
А если я захочу null засетить? Или число/дату? Не очень понимаю, почему вообще тут типы сетятся строкой, а не своим типом 🤔

2021-04-28 07:32 UTC, FrediKats commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +        }
Солидарен. То оставь коммент, что это ок.

2021-04-28 07:45 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +            File.Delete(oldPath);
https://github.com/kysect/SeaInk/pull/29/files/f1abd18ec42665d2baf59f898a279277238665eb#r619872252

2021-04-28 08:02 UTC, hrrrrustic commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +            _workbook.Worksheet(index.SheetName).Cell(index.Row, index.Column).Value = value!.ToString();
А в чем проблема...
Это выглядит как ```Console.WriteLine<T>(T value)```, который внезапно внутри делает ```.ToString```
Ну null засетить это сильно конечно

2021-04-28 08:03 UTC, hrrrrustic commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +            return (T) _workbook.Worksheet(index.SheetName).Cell(index.Row, index.Column).Value;
>А если значение null, оно не упадет на касте? Было бы неплохо, если бы при null значнеии там null и вернулся.
Я прощу прощения, а как ты хочешь вернуть null без каста к типу...

2021-04-28 08:03 UTC, hrrrrustic commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +            var newPath = Path.Combine(Path.GetDirectoryName(_filePath)!, name);
А мог бы наоборот объяснит как настроить...

2021-04-28 08:06 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +            _workbook.Worksheet(index.SheetName).Cell(index.Row, index.Column).Value = value!.ToString();
У меня появился защитник в лице hrrrrustic :)

2021-04-28 08:19 UTC, Ar4eR-ValerA commented
@FrediKats merge

2021-04-28 08:20 UTC, annchous commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +            _workbook.Worksheet(index.SheetName).Cell(index.Row, index.Column).Value = value!.ToString();
учитель ))

2021-04-28 08:24 UTC, FrediKats commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +            return (T) _workbook.Worksheet(index.SheetName).Cell(index.Row, index.Column).Value;
return default;

2021-04-28 08:26 UTC, FrediKats commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +            _workbook.Worksheet(index.SheetName).Cell(index.Row, index.Column).Value = value!.ToString();
> Это выглядит как Console.WriteLine<T>(T value)
Есть нюанс. Когда ты работаешь с консолью - у тебя действительно все является строками. Но в экселе ты хранишь в ячейках их типизированными. Т.е. вот тот Value - это object. Но это не всегда строка. Ну и если я сделаю такой сет интового значения, а потом попытаюсь считать - скорее всего, упаду с тем, что нельзя кастить строку в инт.

2021-04-28 08:29 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/Entities/Division.cs
>              Subject = subject;
Если мою замержить щас, то когда ты замержишь свою ветку, то эти файлы спокойно заменятся на нужные

2021-04-28 08:32 UTC, FrediKats commented
Главное, таски не забудь завести на рефакторинг)

2021-04-28 08:32 UTC, merged

2021-04-28 09:49 UTC, hrrrrustic commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +            return (T) _workbook.Worksheet(index.SheetName).Cell(index.Row, index.Column).Value;
А чем это отличается от (T)null?
Значимые типы не берем конечно, пушт там один хрен придется писать отдельную перегрузку для наллабл

2021-04-28 09:52 UTC, hrrrrustic commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +            _workbook.Worksheet(index.SheetName).Cell(index.Row, index.Column).Value = value!.ToString();
>Value - это object
Понял, дальше не читал. Нет библиотеки нормально шо ле?

2021-04-28 11:29 UTC, FrediKats commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +            return (T) _workbook.Worksheet(index.SheetName).Cell(index.Row, index.Column).Value;
Ну дак я и спросил, не упадет ли.
Ну и написал про перегрузку.

2021-04-28 11:29 UTC, FrediKats commented on Source/SeaInk.Core/Entities/Tables/ExcelTable.cs
> +            _workbook.Worksheet(index.SheetName).Cell(index.Row, index.Column).Value = value!.ToString();
А как ты хочешь типизировать массив массивов из разных элементов?