Refactor: excel table
kysect/SeaInk pull request #40
Opened 2021-05-16 19:14 UTC by Bibletoon

Частично закрываю issue #30, не придумал что делать с дефолтным листом и не нашёл способа изменить переименование таблицы

2021-05-16 19:19 UTC, Ar4eR-ValerA commented
Постараюсь в скором времени прочекать

2021-05-16 19:24 UTC, ronimizy requested changes

2021-05-16 19:24 UTC, ronimizy commented on Source/SeaInk.Core/TableIntegrations/Models/Styles/Enums/LineStyle.cs
> +        Thick,
"Black" это термин начертаний шрифтов, если посмотреть все стили у популярных шрифтов там будет начертание "Black", так что с этим изменением не согласен

2021-05-16 19:24 UTC, ronimizy commented on Source/SeaInk.Core/TableIntegrations/Models/TableIndexRange.cs
> +
Тут должны возвращаться не инты, а TableIndexRange по соответствующим строкам/столбцам

2021-05-16 19:29 UTC, ronimizy commented on Source/SeaInk.Core/TableIntegrations/Models/TableIndexRange.cs
> +
```suggestion
        public IEnumerable EnumerateRows()
        {
            for (int row = From.Row; row < To.Row; row++)
            {
                yield return new TableIndexRange(SheetName, SheetId, (From.Column, row), (To.Column, row));
            }
        }
        
        public IEnumerable EnumerateColumns()
        {
            for (int column = From.Column; column < To.Column; column++)
            {
                yield return new TableIndexRange(SheetName, SheetId, (column, From.Row), (column, To.Row));
            }
        }

```

2021-05-16 19:51 UTC, Bibletoon commented on Source/SeaInk.Core/TableIntegrations/Models/TableIndexRange.cs
> +
Звучит валидно, но есть много методов, где нужно проитерироваться только по индексам, и писать row.From.Row что бы получить индекс строки выглядит не очень красиво. Как насчёт помимо EnumerateRows[Columns] добавить EnumerateRows[Columns]Indexes?

2021-05-16 19:54 UTC, ronimizy commented on Source/SeaInk.Core/TableIntegrations/Models/TableIndexRange.cs
> +
Почему бы и нет, только не Indexes, а Indices)

2021-05-16 20:04 UTC, Bibletoon commented on Source/SeaInk.Core/TableIntegrations/Models/Styles/Enums/LineStyle.cs
> +        Thick,
1.Но это не шрифт, а стиль линии для границы
2.В библиотеках для excel и google таблиц, и в английской версии excel (в google table стили линий просто не подписаны) это называется Thick
![image](https://user-images.githubusercontent.com/45363221/118410943-bdc5ae80-b69a-11eb-911c-f8d8bec7a1db.png)
3.Зачем тащить слово из области шрифтов, которое не используется для границ и просто запутывает?

2021-05-16 20:07 UTC, ronimizy commented on Source/SeaInk.Core/TableIntegrations/Models/Styles/Enums/LineStyle.cs
> +        Thick,
My bad так сказать, сонные глаза играют с мозгом в сломанный телефон…

2021-05-16 20:08 UTC, ronimizy approved these changes

2021-05-16 20:08 UTC, ronimizy commented
Осталось дождаться вердикта Валеры)

2021-05-16 20:09 UTC, Bibletoon commented on Source/SeaInk.Core/TableIntegrations/Models/Styles/Enums/LineStyle.cs
> +        Thick,
То же самое кстати относится к замене Leading/Trailing на Left/Right. У ячейки нет начала, нет конца. Есть право и лево. Я тестил с арабскими шрифтами, с которыми в вёрстке leading и left работают по-разному, таблицам абсолютно плевать, всё сдвигают влево.

2021-05-16 20:22 UTC, Ar4eR-ValerA requested changes

2021-05-16 20:22 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/TableIntegrations/Excel/ExcelTable.cs
> +        }
А что эти методы теперь возвращают? Количестве активных (ну недефолтных) столбцов/строк или количество вообще всех столбцов/строк выделенных в файле? Если второе, тот эти методы по сути имеют не больше смысла, чем возвращение ноля)

2021-05-16 20:22 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/TableIntegrations/Excel/ExcelTable.cs
> +            index.Name = name;
Зачем?0_o

2021-05-16 20:22 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/TableIntegrations/Models/BorderStyle.cs
> +        public LineConfiguration Right { get; set; } = new LineConfiguration();
Лучше оставить leading и trailing, так как это общепринятые обозначения (слова Георгия)

2021-05-16 20:22 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/TableIntegrations/Models/BorderStyle.cs
> +            Right = creator.Create();
Аналогично

2021-05-16 20:22 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/TableIntegrations/Models/BorderStyle.cs
> +            Right = right;
Аналогично

2021-05-16 20:22 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/TableIntegrations/Models/BorderStyle.cs
> +            Right = new LineConfiguration(Color.Black, trailing);
Аналогично

2021-05-16 20:22 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/TableIntegrations/Models/BorderStyle.cs
> +               Right = style.Right.ToGoogleBorder()
Аналогично

2021-05-16 20:22 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/TableIntegrations/Models/Styles/Enums/Alignment.cs
> +        Right,
Бе бе бе бе

2021-05-16 20:23 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/TableIntegrations/Models/Styles/Enums/LineStyle.cs
> +        Thick,
Хм, окей, пусть будет left и right

2021-05-16 20:24 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/TableIntegrations/Models/BorderStyle.cs
> +        public LineConfiguration Right { get; set; } = new LineConfiguration();
Уже увидел ваш диалог с Гошей, окей, оставляй left и right, норм.

2021-05-16 20:28 UTC, Bibletoon commented on Source/SeaInk.Core/TableIntegrations/Excel/ExcelTable.cs
> +            index.Name = name;
Ну в google table так же, да и логично если меняешь имя в таблице, в sheetIndex, который будет потом использоваться, тоже его заменить

2021-05-16 20:37 UTC, Bibletoon commented on Source/SeaInk.Core/TableIntegrations/Excel/ExcelTable.cs
> +        }
Они возвращают последнюю строку/столбец, в которых есть данные. С помощью этой информации можно хоть как-то понять, где в таблице есть данные.

2021-05-16 20:40 UTC, Bibletoon commented on Source/SeaInk.Core/TableIntegrations/Excel/ExcelTable.cs
> +        }
Кстати зачем в эти методы передаётся TableIndex, если что тут, что в google table используется только sheet index. Лучше тогда передавать его, так как если вызываешь метод RowCount/ColumnCount передавая TableIndex, ожидаешь получить информацию не по всей таблице, а по столбцу/строке с конкретной ячейкой
@ronimizy

2021-05-16 20:41 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/TableIntegrations/Excel/ExcelTable.cs
> +        }
Окей, валидно

2021-05-16 20:45 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/TableIntegrations/Excel/ExcelTable.cs
> +            index.Name = name;
Да, ноо....
Это ведь просто параметр у метода, он не изменится потом, когда метод выполнится. Поэтому потом в main'е всё равно придётся менять name у Index.
Тип, если бы index передавался с модификатором out и после метода с ним что-то происходило, то да, нужно было бы менять актуальный идекс внутри метода.
А тут, ну хз, по сути это ни на что не влияет, так что это наверно лишнее.

2021-05-16 20:59 UTC, Bibletoon commented on Source/SeaInk.Core/TableIntegrations/Excel/ExcelTable.cs
> +            index.Name = name;
Нет, не стоит путать C# и C++
В шарпе при передаче ссылочного типа как параметра метода, передаётся копия ссылки на объект. Параметр out это другое.
[Тык](https://metanit.com/sharp/tutorial/2.16.php)

2021-05-17 06:17 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/TableIntegrations/Excel/ExcelTable.cs
> +            index.Name = name;
Ну я это и говорю же, что передаётся копия ссылки. Поэтому как только метод кончится, то, что ты a index.name изменил, ничего не изменит - это всё останется внутри метода не выйдя из неё. В этом случае вопрос, зачем делать то, что не оказывает эффекта за пределами метода?

2021-05-17 06:23 UTC, Bibletoon commented on Source/SeaInk.Core/TableIntegrations/Excel/ExcelTable.cs
> +            index.Name = name;
В предыдущем комменте я добавил ссылку, советую перейти и ознакомиться, ведь там написано:
> При передаче объекта класса по значению в метод передается копия ссылки на объект. Эта копия указывает на тот же объект, что и исходная ссылка, потому мы можем изменить отдельные поля и свойства объекта, но не можем изменить сам объект.

2021-05-17 06:30 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/TableIntegrations/Excel/ExcelTable.cs
> +            index.Name = name;
Окей

2021-05-17 06:30 UTC, Ar4eR-ValerA approved these changes

2021-05-17 06:35 UTC, ronimizy commented on Source/SeaInk.Core/TableIntegrations/Models/BorderStyle.cs
> +        public LineConfiguration Right { get; set; } = new LineConfiguration();
Я сдался, он был убедительным)

2021-05-17 06:39 UTC, merged