Restructure
kysect/SeaInk pull request #47
Opened 2021-08-09 19:31 UTC by ronimizy

2021-08-10 05:42 UTC, Bibletoon requested changes
Добрый pr. Старый функционал уже выпилили, новый ещё не добавили

2021-08-10 05:42 UTC, Bibletoon commented on .gitignore
> -/Source/.idea/
Зачем урезать гитигнор? Он теперь кривой
![](https://i.imgur.com/1roTXrO.png)

2021-08-10 05:42 UTC, Bibletoon commented on Source/SeaInk.Infrastructure/Extensions/AddTestServicesExtension.cs
> +                .AddSingleton(new DatabaseContext(options))
А почему не через: 
`services.AddDbContext<DatabaseContext>(o => { o.UseInMemoryDatabase(databaseName); });`
Да и добавлять базу синглтоном как-то супер meh

2021-08-10 05:42 UTC, Bibletoon commented on Source/SeaInk.Infrastructure/Extensions/AddTestServicesExtension.cs
> +                .AddSingleton<IEntityRepository<StudentAssignmentProgress>, DbStudentAssignmentProgressRepository>();
Как-то слишком много синглтонов

2021-08-10 05:42 UTC, Bibletoon commented on Source/SeaInk.sln
> -Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "SeaInk.Sample", "SeaInk.Sample\SeaInk.Sample.csproj", "{0EBBE205-9FAC-4691-820B-92C232D774F5}"
Почему из солюшена проекты удалил, а сами папки оставил

2021-08-10 05:42 UTC, Bibletoon commented on Source/SeaInk.Infrastructure/APIs/ITestUniversitySystemApi.cs
> +        public int TotalCallCount { get; }
Как говорил классик:
~~public~~

2021-08-10 06:52 UTC, FrediKats requested changes

2021-08-10 06:52 UTC, FrediKats commented on .gitignore
> -/Source/.idea/
А это вы ещё в студии не запускали...

2021-08-10 06:52 UTC, FrediKats commented on Source/SeaInk.Core/Entities/StudyAssignment.cs
> +        public int UniversityId { get; init; }
Что такое UniversityId?

2021-08-10 06:52 UTC, FrediKats commented on Source/SeaInk.Core/Models/AssignmentProgress.cs
> +    [Owned]
Что это за атрибут?

2021-08-10 06:52 UTC, FrediKats commented on Source/SeaInk.Core/Models/AssignmentProgress.cs
> +        [Column("CompletionDate")]
А зачем? Он сам не поймёт?

2021-08-10 06:52 UTC, FrediKats commented on Source/SeaInk.Core/Models/AssignmentProgress.cs
> +    public record AssignmentProgress
В чём смысл рекорда, если всё сделано как класс?

2021-08-10 06:52 UTC, FrediKats commented on Source/SeaInk.Core/Repositories/IEntityRepository.cs
> +    public interface IEntityRepository<TEntity> where TEntity: IEntity
А ты уверен, что тебе эти репо нужны? Ты работаешь с EF, который и так является реализацией паттерна Repository. У тебя методы Update/Delete будут просто вызывать другие Update/Delete. Никакого профита особо нет.

2021-08-10 06:57 UTC, ronimizy commented on Source/SeaInk.Core/Entities/StudyAssignment.cs
> +        public int UniversityId { get; init; }
UniversityId = Id в базе университета

2021-08-10 07:04 UTC, ronimizy commented on Source/SeaInk.Core/Repositories/IEntityRepository.cs
> +    public interface IEntityRepository<TEntity> where TEntity: IEntity
Отдельный интерфейс под это даёт возможность, на этапе написания тестов, зафейкать репозиторий

2021-08-10 07:07 UTC, ronimizy commented on Source/SeaInk.Core/Models/AssignmentProgress.cs
> +    [Owned]
Фактически распиливает класс на колонки в таблице класса, содержащего его. Сделал чтобы для AssignmentProgress не заводить отдельную таблицу, сохраняя при этом существующую структуру StudentAssignmentProgress

2021-08-10 07:11 UTC, Bibletoon commented on .gitignore
> -/Source/.idea/
Я запускал, она вроде как ничего не добавила

2021-08-10 07:20 UTC, ronimizy commented on Source/SeaInk.Infrastructure/APIs/ITestUniversitySystemApi.cs
> +        public int TotalCallCount { get; }
Рили

2021-08-10 07:24 UTC, ronimizy commented on Source/SeaInk.Infrastructure/Extensions/AddTestServicesExtension.cs
> +                .AddSingleton<IEntityRepository<StudentAssignmentProgress>, DbStudentAssignmentProgressRepository>();
Предлагаешь поменять их лайфтайм?

2021-08-10 07:28 UTC, ronimizy commented on Source/SeaInk.Core/Repositories/IEntityRepository.cs
> +    public interface IEntityRepository<TEntity> where TEntity: IEntity
Плюс, если так не делать, EF будет растекаться по другим проектам, что не то чтобы очень чисто

2021-08-10 07:32 UTC, Bibletoon commented on Source/SeaInk.Infrastructure/Extensions/AddTestServicesExtension.cs
> +                .AddSingleton<IEntityRepository<StudentAssignmentProgress>, DbStudentAssignmentProgressRepository>();
А, ой, я не заметил, что это конфигурация для тестов. Мне показалось что это конфигурация при запуске сервера, и там делать все репозитории синглтонами явно идея не очень.

2021-08-10 14:00 UTC, ronimizy commented on Source/SeaInk.Infrastructure/Extensions/AddTestServicesExtension.cs
> +                .AddSingleton<IEntityRepository<StudentAssignmentProgress>, DbStudentAssignmentProgressRepository>();
Думаю всё равно на Scoped переделаю

2021-08-10 14:14 UTC, Bibletoon approved these changes

2021-08-10 14:14 UTC, Bibletoon commented on Source/SeaInk.Infrastructure/Extensions/AddTestServicesExtension.cs
> +                .AddDbContext<DatabaseContext>(o => o.UseInMemoryDatabase("SeaInk"))
```suggestion
                .AddDbContext<DatabaseContext>(o => o.UseInMemoryDatabase(databaseName))
```

2021-08-10 14:16 UTC, ronimizy commented on Source/SeaInk.Infrastructure/Extensions/AddTestServicesExtension.cs
> +                .AddDbContext<DatabaseContext>(o => o.UseInMemoryDatabase("SeaInk"))
Рили

2021-08-10 14:19 UTC, Bibletoon submitted a review, later dismissed
Да я же апрувнул, зачем ререквестить после одного коммита...

2021-08-10 14:20 UTC, ronimizy commented
Это гх сбросил апнув, а галочку зелёную то видеть хочется

2021-08-11 08:31 UTC, FrediKats approved these changes
Мне кажется, что местами с EF будет больно. А с Owned - что-то непонятное. Расскажи хоть в чате людям что это и зачем, потому что будут вопросы.

2021-08-11 11:12 UTC, MGSDS commented on Source/SeaInk.Core/Entities/User.cs
> +    public class User: IUniversityEntity
Мне не очень понятен нейминг. Почему для того чтобы IEntity имело UniversityId нужно создавать дочерний класс IUniversityEntity, а User и так имеет UniversityId. Не логичней ли будет переименовать IUser в IUniversityUser

2021-08-11 11:28 UTC, ronimizy commented on Source/SeaInk.Core/Entities/User.cs
> +    public class User: IUniversityEntity
В общем, сам вопрос мне не совсем понятен, так что просто поясню за нейминг)
IEntity - сущность в нашей базе данных
IUniversityEntity - сущность в базе данных университета

Все, что имеет Id в нашей бд - IEntity
Всё, что имеет Id в бд университета - IUniversityEntity


Смысла делать что-то типа UniversityUser нет, так как нет просто User. Поэтому он сразу просто User.

2021-08-11 16:11 UTC, MGSDS submitted a review, later dismissed

2021-08-11 16:11 UTC, MGSDS commented on Source/SeaInk.Core/Entities/User.cs
> +    public class User: IUniversityEntity
Ок, понял, принял, осознал

2021-08-11 16:52 UTC, Ar4eR-ValerA commented on Source/SeaInk.Infrastructure/APIs/FakeUniversitySystemApi.cs
> +        public List<Division> Divisions { get; } = new();
Мы вроде оговаривали больше не делать сокращённого new().

2021-08-11 16:53 UTC, ronimizy commented on Source/SeaInk.Infrastructure/APIs/FakeUniversitySystemApi.cs
> +        public List<Division> Divisions { get; } = new();
тут прям супер evident какой тип, считается что норм

2021-08-11 16:54 UTC, Ar4eR-ValerA commented on Source/SeaInk.Tests.Infrastructure/EntityFrameworkTests.cs
> +        public void DivisionRepositoryTest_DivisionAddedToDatabase()
Мне понадобилось капец напрячь глаза, чтобы это прочитать. И это норм совмещать CamelCase и snake_case? Или тут тип логическое разделение?

2021-08-11 16:54 UTC, ronimizy commented on Source/SeaInk.Tests.Infrastructure/EntityFrameworkTests.cs
> +        public void DivisionRepositoryTest_DivisionAddedToDatabase()
Да, это нейминг тестов

2021-08-11 16:55 UTC, Bibletoon commented on Source/SeaInk.Tests.Infrastructure/EntityFrameworkTests.cs
> +        public void DivisionRepositoryTest_DivisionAddedToDatabase()
В тестах это ок, там нейминг строится по принципу: ДелаемШтуку_ДолжноПолучитьсяЭто

2021-08-11 18:27 UTC, annchous approved these changes

2021-08-11 18:29 UTC, merged

2021-08-15 08:38 UTC, ronimizy commented
Closes #30

2021-08-15 08:39 UTC, ronimizy commented
Closes #16