Mentor controller
kysect/SeaInk pull request #48
Opened 2021-08-12 14:14 UTC by MGSDS

closes #27

2021-08-12 15:00 UTC, Bibletoon commented on Source/SeaInk.Endpoints/Server/Properties/launchSettings.json
> +      "launchBrowser": false,
Осуждаю

2021-08-12 15:01 UTC, Bibletoon commented on Source/SeaInk.Infrastructure/APIs/FakeUniversitySystemApi.cs
>              _userFaker = new Faker<User>("ru")
Патриотично

2021-08-12 15:07 UTC, ronimizy requested changes
1. Думаю стоит сделать DTO record`ами
2. Получение информации напрямую из API не совсем то, что стоит делать. Доступ должен происходить через `DatabaseContext`, надо будет сделать механизм синхронизации `IUniversitySystemApi` с `DatabaseContext`!

2021-08-12 15:07 UTC, ronimizy commented on Source/SeaInk.Endpoints.Shared/Dto/SubjectDto.cs
> +        }
Опять же

2021-08-12 15:08 UTC, MGSDS commented on Source/SeaInk.Endpoints.Shared/Dto/StudentDto.cs
> +        public string MiddleName { get; set; }
Я скопировал из Student

2021-08-12 15:08 UTC, ronimizy commented on Source/SeaInk.Endpoints.Shared/Dto/StudentDto.cs
> +        public string MiddleName { get; set; }
В этом вопросе пришли к тому, что так его реально называют, так что оставим

2021-08-12 15:09 UTC, MGSDS commented on Source/SeaInk.Endpoints.Shared/Dto/StudentDto.cs
> +            GroupId = -1;
Конструктор по умолчанию делает инвалидный объект, почему нет?

2021-08-12 15:11 UTC, ronimizy commented on Source/SeaInk.Endpoints/Server/Controllers/MentorController.cs
> +            }
А можно просто 
```suggestion
            Mentor mentor =  _api.GetMentor(mentorId);
            if (mentor is null)
                return new List<SubjectDto>();
                    
            List<Division> mentorDivisions = mentor.Divisions;
            return mentorDivisions.Select(x => new SubjectDto(x.Subject)).ToList();
```

2021-08-12 15:12 UTC, MGSDS commented on Source/SeaInk.Endpoints/Server/Properties/launchSettings.json
> +      "launchBrowser": false,
@ronimizy тебя тут осуждают)

2021-08-12 15:12 UTC, ronimizy commented on Source/SeaInk.Endpoints/Server/Controllers/MentorController.cs
> +            }
И во втором так же

2021-08-12 15:13 UTC, ronimizy commented on Source/SeaInk.Endpoints/Server/Properties/launchSettings.json
> +      "launchBrowser": false,
Бывает

2021-08-12 15:15 UTC, MGSDS commented on Source/SeaInk.Endpoints.Shared/Dto/StudyGroupDto.cs
> +        public List<StudentDto> Students { get; set; }
Согласен

2021-08-12 15:23 UTC, MGSDS commented on Source/SeaInk.Endpoints.Shared/Dto/StudentDto.cs
> +        [Key] public int Id { get; set; }
По-моему логично, когда главная характеристика студента - его id

2021-08-12 15:26 UTC, MGSDS commented on Source/SeaInk.Endpoints.Shared/Dto/StudyGroupDto.cs
> +        public List<StudentDto> Students { get; set; }
Как заметил Bibletoon IEnumerable будет здесь лучше

2021-08-12 15:26 UTC, MGSDS commented on Source/SeaInk.Endpoints.Shared/Dto/SubjectDto.cs
> +        public  List<StudyAssignmentDto> Assignments { get; set; }
Как заметил Bibletoon IEnumerable будет здесь лучше

2021-08-12 15:34 UTC, MGSDS commented on Source/SeaInk.Endpoints.Shared/Dto/StudyAssignmentDto.cs
> +    public class StudyAssignmentDto
Я спрашивал, потом класс может измениться или требования к это поменяются и Dto не будет повторять класс

2021-08-12 15:37 UTC, MGSDS commented on Source/SeaInk.Endpoints.Shared/Dto/StudentDto.cs
> +            GroupId = -1;
Или конструкторы по умолчанию не нужны?

2021-08-12 15:48 UTC, MGSDS commented on Source/SeaInk.Endpoints/Client/ControllerClients/MentorControllerClient.cs
> +            _caseInsensitiveOptions = new JsonSerializerOptions
Может, не стоит задавать глобально т.к. может, где-то в другом месте проекта нужен будет case sensivtive JsonSerializer?

2021-08-12 15:48 UTC, MGSDS commented on Source/SeaInk.Endpoints/Server/Controllers/MentorController.cs
> +                return mentorDivisions.Select(x => new SubjectDto(x.Subject)).ToList();
Может, это стоит оформить отдельной таской?

2021-08-12 17:24 UTC, ronimizy commented on Source/SeaInk.Endpoints/Client/ControllerClients/MentorControllerClient.cs
> +            _caseInsensitiveOptions = new JsonSerializerOptions
Тогда уж хотя бы делай их `static readonly` незачем по каждому инстансу таскать

2021-08-12 17:26 UTC, ronimizy commented on Source/SeaInk.Endpoints.Shared/Dto/StudyAssignmentDto.cs
> +    public class StudyAssignmentDto
Валидно

2021-08-12 17:29 UTC, ronimizy commented on Source/SeaInk.Endpoints.Shared/Dto/StudentDto.cs
> +            GroupId = -1;
Он не то, чтобы совсем инвалидный, значения у него есть, так что его использование просто будет давать неверные результаты, вместо `NullReferenceException` при попытке получить значения его членов.
Конструктор по умолчанию тут наверное как раз и не нужен, так как эта штука будет преобразовываться из сущности, а не конструироваться почленно.

2021-08-12 17:30 UTC, ronimizy commented on Source/SeaInk.Endpoints.Shared/Dto/StudentDto.cs
> +        [Key] public int Id { get; set; }
```suggestion
        public int Id { get; set; }
```

2021-08-12 17:31 UTC, MGSDS commented on Source/SeaInk.Infrastructure/APIs/FakeUniversitySystemApi.cs
>              _userFaker = new Faker<User>("ru")
Ну типа

2021-08-12 17:35 UTC, ronimizy commented on Source/SeaInk.Endpoints.Shared/Dto/StudyAssignmentDto.cs
> +    }
Покажу на примере одного, остальные сам переделаешь
https://docs.microsoft.com/ru-ru/dotnet/csharp/whats-new/tutorials/records

```suggestion
    public record StudyAssignmentDto(int Id, string Title, bool IsMilestone, 
                                                                 DateTime StartDate, DateTime EndDate,
                                                                 float MinPoints, float MaxPoints)
    {
        public StudyAssignmentDto(StudyAssignment sa)
        {
            Id = sa.Id;
            Title = sa.Title;
            IsMilestone = sa.IsMilestone;
            StartDate = sa.StartDate;
            EndDate = sa.EndDate;
            MinPoints = sa.MinPoints;
            MaxPoints = sa.MaxPoints;
        }
    }
```

2021-08-13 08:05 UTC, ronimizy commented on Source/SeaInk.Endpoints/Server/Controllers/MentorController.cs
> +        }
Эээммммм, это ты в джаве такого понабрался?

2021-08-13 08:44 UTC, ronimizy requested changes
Думаю есть смысл MentorController переименовать в MentorsController, так как он управляет не одним ментором, а всеми

2021-08-13 08:44 UTC, ronimizy commented on Source/SeaInk.Endpoints.Shared/Dto/StudyAssignmentDto.cs
> +        }
```suggestion
        public static StudyAssignmentDto ToDto(this StudyAssignment assignment)
        {
            return new StudyAssignmentDto(assignment.Id, assignment.Title, assignment.IsMilestone, assignment.StartDate, assignment.EndDate,
                assignment.MinPoints, assignment.MaxPoints);
        }
```

2021-08-13 08:44 UTC, ronimizy commented on Source/SeaInk.Endpoints/Client/ControllerClients/MentorControllerClient.cs
> +            }
`await` внутри скобок - плохо. introduce local variable

2021-08-13 08:44 UTC, ronimizy commented on Source/SeaInk.Endpoints/Client/ControllerClients/MentorControllerClient.cs
> +            }
same

2021-08-13 08:44 UTC, ronimizy commented on Source/SeaInk.Endpoints/Server/Controllers/MentorController.cs
> +        }
...

2021-08-13 08:46 UTC, MGSDS commented on Source/SeaInk.Endpoints/Server/Controllers/MentorController.cs
> +        }
да бл, я забыл этот файл закоммитить

2021-08-13 08:47 UTC, ronimizy commented on Source/SeaInk.Endpoints/Server/Controllers/MentorController.cs
> +        }
Удали GitKraken

2021-08-13 08:48 UTC, MGSDS commented on Source/SeaInk.Endpoints/Server/Controllers/MentorController.cs
> +        }
No. Мои кривые руки не означают, что gitkeaken - зло

2021-08-13 09:01 UTC, ronimizy commented on Source/SeaInk.Endpoints/Server/Controllers/MentorController.cs
> +        }
Нет, но он кладет перед ними функциональность которой не надо пользоваться. Сомневаюсь что тебе **нужно** юзать что-то кроме commit и push, дроп и ему подобные нужны в крайнем случае, если что-то сильно зафакапилось, а у тебя игра с гитом становится нормальной практикой.

2021-08-13 09:08 UTC, MGSDS commented on Source/SeaInk.Endpoints/Server/Controllers/MentorController.cs
> +        }
No. Ты не прав. Тот же функционал предоставляет и rider и git-cli, gitkraken удобен хорошим gui

2021-08-13 09:45 UTC, ronimizy commented on Source/SeaInk.Endpoints/Server/Controllers/MentorController.cs
> +        }
> он кладет перед ними функциональность которой не надо пользоваться
> gitkraken удобен хорошим gui

А я о чём?

2021-08-13 10:23 UTC, MGSDS commented
@ronimizy может, DbContext сделаем другой ишуей? Я ее возьму сразу после мертва этого pr.

2021-08-13 10:25 UTC, ronimizy commented
> @ronimizy может, DbContext сделаем другой ишуей? Я ее возьму сразу после мертва этого pr.

Я бы так не делал, так как текущий код концептуально неверен. Опрости остальных в чате, если большинство будет за, то ок, сделаешь другой ишуёй.

2021-08-13 11:31 UTC, MGSDS commented on Source/SeaInk.Endpoints/Client/Program.cs
> +            builder.Services.AddScoped(_ => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
Хз, я погуглил немного, нашел ток подобную реализацию

2021-08-15 15:14 UTC, FrediKats commented on Source/SeaInk.Endpoints.Shared/Dto/StudentDto.cs
> +            GroupId = -1;
NRE не будет, это не ссылочные типы. Имхо, в данном случае разницы особо нет будет там default value или -1. Конструктор, _скорее всего_ нужен т.к. без него может умереть сериализация. Но такая логика с -1 вызывает у меня вопросы.

2021-08-15 15:15 UTC, FrediKats commented on Source/SeaInk.Endpoints.Shared/Dto/StudyGroupDto.cs
> +        public List<StudentDto> Students { get; set; }
Есть нюансы. Как минимум, IEnumerable не является коллекцией. И использовать его для хранения множества не стоит. IReadOnlyCollection - возможно, но не IEnumerable.

2021-08-15 15:17 UTC, FrediKats commented on Source/SeaInk.Endpoints/Client/ControllerClients/MentorControllerClient.cs
> +            _caseInsensitiveOptions = new JsonSerializerOptions
Можно через DI прокинуть настройки.

2021-08-15 15:17 UTC, FrediKats commented on Source/SeaInk.Endpoints/Client/Program.cs
> +            builder.Services.AddScoped(_ => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
`builder.Services.AddHttpClient`

2021-08-15 15:18 UTC, FrediKats commented on Source/SeaInk.Endpoints/Server/Controllers/MentorController.cs
> +                return mentorDivisions.Select(x => new SubjectDto(x.Subject)).ToList();
Заведите ишую на добавлени мапера.

2021-08-15 15:18 UTC, FrediKats commented on Source/SeaInk.Endpoints/Server/Properties/launchSettings.json
> +      "launchBrowser": false,
А зачем это было сделано?

2021-08-15 15:19 UTC, FrediKats commented on Source/SeaInk.Endpoints.Shared/Dto/StudentDto.cs
> +        [Key] public int Id { get; set; }
Плюсую на счёт того, что в DTO это не очень значимый атрибут.

2021-08-15 15:21 UTC, FrediKats commented on Source/SeaInk.Endpoints.Shared/Dto/StudyAssignmentDto.cs
> +    public class StudyAssignmentDto
Да, стоит. Как минимум, потому что у тебя будет три проекта: Back Front Sdk. В последнем будут лежать шаренные типы, которые используются. Например, Dto. Но в SDK будет не правильно уносить сущности. А если не уносить, то тогда в проекте фронта не будет возможности с ними работать.

2021-08-15 15:21 UTC, FrediKats commented on Source/SeaInk.Endpoints.Shared/Dto/StudyGroupDto.cs
> +        public List<StudentDto> Students { get; set; }
Поддерживаю Гошу. Выше написал почему.

2021-08-15 15:25 UTC, FrediKats commented on Source/SeaInk.Endpoints/Server/Controllers/MentorController.cs
> +        }
В качестве штрафа за токс напишите совместный пост на тему "props'n'cons of GUI/Console git".
@ronimizy @MGSDS

2021-08-15 15:31 UTC, FrediKats requested changes

2021-08-15 15:31 UTC, FrediKats commented on Source/SeaInk.Endpoints.Shared/Dto/StudentDto.cs
> +    public record StudentDto(int Id, string FirstName, string LastName, string MiddleName, string FullName, int GroupId,
Если много аргументов, то пиши их в столбик, чтобы было проще читать и diff смотреть.

2021-08-15 15:31 UTC, FrediKats commented on Source/SeaInk.Endpoints/Server/Controllers/MentorController.cs
> +            _api = universitySystemApi;
@ronimizy кажется об этом писал. Алгоритм работы должен выстраиваться вокруг взаимодействия клиента и сервера. Когда мы говорим о запросах на получение данных, то мы должны пойти в базу и эти данные взять. Наша система должна пытаться существовать автономно.
Что касается внешнего API - мы должны отдельно реализовать синхронизацию, это правда. Но это отдельной таской и когда будет API.

2021-08-15 15:37 UTC, FrediKats commented on Source/SeaInk.Endpoints/Server/Controllers/MentorController.cs
> +            _api = universitySystemApi;
Но это не часть этой ишуи. Заведите другую, на именно эту логику.

2021-08-15 15:37 UTC, MGSDS commented on Source/SeaInk.Endpoints/Client/Program.cs
> +            builder.Services.AddScoped(_ => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
@FrediKats иде так не считает...
<img width="267" alt="Screenshot 2021-08-15 at 18 37 10" src="https://user-images.githubusercontent.com/40380619/129484012-a0b93773-2837-44da-9d59-93be3699005f.png">

2021-08-15 18:03 UTC, ronimizy requested changes

2021-08-15 18:03 UTC, ronimizy commented on Source/SeaInk.Endpoints.Shared/Dto/StudentDto.cs
> +        string LastName,
```suggestion
    public record StudentDto(
        int Id,
        string FirstName,
        string LastName,
```

2021-08-15 18:03 UTC, ronimizy commented on Source/SeaInk.Endpoints/Client/ControllerClients/MentorControllerClient.cs
> +        };
@FrediKats правильно сказал, лучше через di прокидывать, будут ещё контроллеры, придётся каждый раз это писать

2021-08-15 18:03 UTC, ronimizy commented on Source/SeaInk.Endpoints/Server/Controllers/MentorController.cs
> +        }
_databaseContext

2021-08-15 18:33 UTC, ronimizy requested changes

2021-08-15 18:33 UTC, ronimizy commented on Source/SeaInk.Endpoints/Client/ControllerClients/MentorControllerClient.cs
> +        private JsonSerializerOptions _jsonSerializerOptions;
```suggestion
        private readonly JsonSerializerOptions _jsonSerializerOptions;
```

2021-08-15 18:33 UTC, ronimizy commented on Source/SeaInk.Endpoints/Client/Program.cs
> +            builder.Services.AddSingleton(_ => new JsonSerializerOptions {PropertyNameCaseInsensitive = true});
```suggestion
            builder.Services.AddSingleton(_ => new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
```

2021-08-15 18:44 UTC, ronimizy approved these changes

2021-08-15 23:36 UTC, FrediKats commented
Если @ronimizy заапрувил, то можете меня не ждать. Я просто поверю, что вы учли мои замечания :3

2021-08-15 23:41 UTC, annchous requested changes

2021-08-15 23:41 UTC, annchous commented on Source/SeaInk.Endpoints/Server/Controllers/MentorController.cs
> +            return mentorDivisions
```suggestion
            return mentor.Divisions
```
Тут вроде как лист этот не особо полезный

2021-08-15 23:41 UTC, annchous commented on Source/SeaInk.Endpoints/Server/Controllers/MentorController.cs
> +        [HttpGet("{mentorId}/subject/{subjectId}/groups")]
```suggestion
        [HttpGet("{mentorId}/subjects/{subjectId}/groups")]
```

2021-08-15 23:41 UTC, annchous commented on Source/SeaInk.Endpoints.Shared/Dto/StudentDto.cs
> +        }
```suggestion
        public static StudentDto ToDto(this Student student)
        {
            return new StudentDto(
                student.Id, 
                student.FirstName, 
                student.LastName, 
                student.MiddleName,
                student.FullName, 
                student.Group.Id, 
                student.Group.Name);
        }
```

2021-08-15 23:41 UTC, annchous commented on Source/SeaInk.Endpoints/Server/Controllers/MentorController.cs
> +            return mentorDivisions.Select(x => x.Subject.ToDto()).ToList();
```suggestion
            return mentor.Divisions.Select(x => x.Subject.ToDto()).ToList();
```

2021-08-16 05:27 UTC, annchous approved these changes
Просили понять и простить. Прощаем.

2021-08-16 05:36 UTC, Bibletoon approved these changes

2021-08-16 06:15 UTC, FrediKats commented
Ишую на рефакторинг заведите только. Не зря же человек ревьювил!

2021-08-16 06:15 UTC, FrediKats approved these changes

2021-08-16 06:16 UTC, merged

2021-08-16 11:07 UTC, hrrrrustic commented on Source/SeaInk.Endpoints.Shared/Dto/StudentDto.cs
> +        [Key] public int Id { get; set; }
_Атрибут [Key] - атрибут для EF_ 
Это неправда. Атрибут не имеет никакого прямого отношения к EF

2021-08-16 11:09 UTC, hrrrrustic commented on Source/SeaInk.Endpoints.Shared/Dto/StudyGroupDto.cs
> +        public List<StudentDto> Students { get; set; }
Аж слезу пустил от этого треда

2021-08-16 11:14 UTC, ronimizy commented on Source/SeaInk.Endpoints.Shared/Dto/StudentDto.cs
> +        [Key] public int Id { get; set; }
@hrrrrustic "арибут для EF" значит что в сущностях он используется для EF, прямого отношения к EF он не имеет, но я об этом и не говорил)