Логика генерация таблиц
kysect/SeaInk pull request #63
Opened 2021-08-28 19:22 UTC by Ar4eR-ValerA

Closes #6 
При создании забиваются все работы (у нужных выбирается, что они важные, типа рубежки) и  дедлайны. Потом можно добавлять студентов.

Метод авторизации и синхронизации с гугл аккаунтом выглядит очень коряво и вероятно будет работать только, если потанцевать с бубном вокруг гугла. Чтобы на своём компе опробовать то, что я написал в итоге, думаю придётся потыкать @ronimizy, чтобы он показал, что нужно сделать с гуглом.  Потом разумеется этот метод не нужен будет, ибо всё будет через сервер.

2021-08-28 20:14 UTC, FrediKats requested changes
Я просто мимокрокодил, пару замечаний оставил. Пока код мне не понятен.

2021-08-28 20:14 UTC, FrediKats commented on Source/SeaInk.Core/TableGenerationService/ColumnGenerator.cs
> +            var dataIndex = new SheetIndexRange(new SheetIndex(ColumnConfiguration.Range.From.Column, new RowIndex(2)));
Что за (2)? И кажется, что нужно инкапсулировать логику создания изменённых индексов. Можно вдохновиться рекордами с их with

2021-08-28 20:14 UTC, FrediKats commented on Source/SeaInk.Core/TableGenerationService/ColumnGenerator.cs
> +                    break;
А почему мы не конфигурируем стили в CreateColumn?

2021-08-28 20:30 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/TableGenerationService/SheetGenerator.cs
> +            //Всё в тестовом варианте, потом это будет на сервере, нужно будет исправить разумеется
Я к сожалению тоже не особо, это скинул Гоша, чтобы работало с гугл таблицей. Я не стал изобретать велосипед и кинул это всё в авторизацию. И да, это временно, я добавлю TODO.
@ronimizy, поясни за то, что тут происходит)

2021-08-28 20:31 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/Models/ColumnConfiguration.cs
> +        public string DeadLine { get; }
Я не проверял, нормально ли это конвертится в инфу для гугл таблиц. Проверю, и если норм работает, заменю.

2021-08-28 20:32 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/TableGenerationService/SheetGenerator.cs
> +                    new SheetIndex(new ColumnIndex(1 + i), new RowIndex(3))
Захардкодил то, что таблица у меня начинается с третьей строки (ну заголовки все). Чтобы сверху было место для всякого.

2021-08-28 20:33 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/TableGenerationService/ColumnGenerator.cs
> +            var dataIndex = new SheetIndexRange(new SheetIndex(ColumnConfiguration.Range.From.Column, new RowIndex(2)));
Захардкодил место для дедлайнов. Так как они всегда будут на второй строке.

2021-08-28 20:34 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/TableGenerationService/ColumnGenerator.cs
> +            var dataIndex = new SheetIndexRange(new SheetIndex(ColumnConfiguration.Range.From.Column, new RowIndex(2)));
Насчёт инкапсуляции логики, окей, займусь.

2021-08-28 20:34 UTC, ronimizy commented on Source/SeaInk.Core/TableGenerationService/SheetGenerator.cs
> +            //Всё в тестовом варианте, потом это будет на сервере, нужно будет исправить разумеется
Конкретно в выделенных строчках мы инициализируем сервисы

2021-08-28 20:36 UTC, ronimizy commented on Source/SeaInk.Core/TableGenerationService/ColumnGenerator.cs
> +            var dataIndex = new SheetIndexRange(new SheetIndex(ColumnConfiguration.Range.From.Column, new RowIndex(2)));
Я как раз подразумевал что с индексами будут с помощью `with` будут работать)

2021-08-28 20:36 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/TableGenerationService/ColumnGenerator.cs
> +                    break;
Я из той логики, что сначала создаётся скелет таблицы, без студентов. Там везде выделение одинаковое. А потом добавляются студенты, поэтому нужно делать стили тут. Типо, изначально количество студентов неизвестно, и их добавление - это отдельное действие. Так и в целом к уже существующей группе проще добавлять студентов.

2021-08-28 20:37 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/TableGenerationService/ColumnGenerator.cs
> +            var dataIndex = new SheetIndexRange(new SheetIndex(ColumnConfiguration.Range.From.Column, new RowIndex(2)));
Пора мне прочитать, что такое with. Окей

2021-08-28 21:33 UTC, ronimizy requested changes
Не нравятся функции создания колонок, слишком кромоздкое заполнение стилей, а при создании самих колонок есть лишний (в некоторых случаях) запрос на создание дедлайна. Надо как-то инкапсулировать эту  логику в конфигурации, либо наследованием, либо при помощи стратегии + фабричный метод. (Советую второе)
Слишком много хардкодов, если считаешь что где-то может понадобиться отступ или типа того - добавь в конфигурацию 
Во всех классах внедряемые объекты `public { get; }`, а не `private readonly`, какие на это причины?

2021-08-30 18:45 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/SeaInk.Core.csproj
>      <PackageReference Include="ClosedXML.Report" Version="0.2.2" />
Nope

2021-09-01 20:46 UTC, ronimizy reviewed
«отрисовка» вся должна быть асинхронной правда. сделай на рефактор тасочку, потом возьмёшь, или кто-то другой возьмёт

2021-09-01 20:46 UTC, ronimizy commented on Source/SeaInk.Core/TableGeneration/Authorisation.cs
> +        public static async Task<Sheet> AuthorizeSheet()
Это конечно хорошо что оно тестовое, но встраивать на сервер это как-то надо. В di потом обернём, пока декомпозируй этот метод во что-то реюзабельное

2021-09-01 20:46 UTC, ronimizy commented on Source/SeaInk.Core/TableGeneration/Authorisation.cs
> +            var spreadsheet = sheetsService.GetSpreadsheet(sheetFile);
у этих методов есть асинхронные перегрузки

2021-09-01 20:46 UTC, ronimizy commented on Source/SeaInk.Core/TableGeneration/ColumnConfigurations/ColumnConfigurationBase.cs
> +        public SheetIndex Draw(Sheet sheet, SheetIndex start)
добавь док про то, какой индекс возвращается

2021-09-01 20:46 UTC, ronimizy commented on Source/SeaInk.Core/TableGeneration/ColumnConfigurations/ListColumnConfiguration.cs
> +
какая дыра, чуть не упал

2021-09-02 09:09 UTC, Bibletoon commented on Source/SeaInk.Core/TableGeneration/ColumnConfigurations/ColumnConfigurationBase.cs
> +        public SheetIndex Draw(Sheet sheet, SheetIndex start)
Да, без доки сложно понять, что за магия с индексами

2021-09-03 15:54 UTC, ronimizy requested changes
Как-то с авторизацией лишняя абстракция и лишнее обёртывание, из всего этого стоит оставить метод получения сервиса.
Почитай про NUnit и переделай всё что у тебя в сэмпле на тест

2021-09-03 15:54 UTC, ronimizy commented on Source/SeaInk.Core/TableGeneration/ColumnConfigurations/ColumnConfigurationBase.cs
> +        /// <param name="start"></param>
Я бы разбил общее описание на описания каждого аргумента

2021-09-03 15:54 UTC, ronimizy commented on Source/SeaInk.Core/TableGeneration/ColumnConfigurations/ListColumnConfiguration.cs
> +            var range = new SheetIndexRange(start, start with {Row = start.Row + _size - 1});
introduce local variable

2021-09-03 16:46 UTC, Ar4eR-ValerA commented
> Как-то с авторизацией лишняя абстракция и лишнее обёртывание (ты по сути заменяешь одну строку на 3), из всего этого стоит оставить метод получения сервиса.
> 
> Почитай про NUnit и переделай всё что у тебя в сэмпле на тест 
Может это в таску залить?)
А это вмерджим?

2021-09-03 16:46 UTC, Ar4eR-ValerA commented
> Как-то с авторизацией лишняя абстракция и лишнее обёртывание (ты по сути заменяешь одну строку на 3), из всего этого стоит оставить метод получения сервиса.
> 
> Почитай про NUnit и переделай всё что у тебя в сэмпле на тест 



Давай это в таску отдельную (для меня). А это уже вмерджим?

2021-09-03 16:48 UTC, ronimizy commented
> > Как-то с авторизацией лишняя абстракция и лишнее обёртывание (ты по сути заменяешь одну строку на 3), из всего этого стоит оставить метод получения сервиса.
> > Почитай про NUnit и переделай всё что у тебя в сэмпле на тест
> 
> Давай это в таску отдельную (для меня). А это уже вмерджим?

Ок, про тесты сделай в отдельную таску, а вот с авторизацией надо сейчас разобраться, то что есть - оч плохо

2021-09-04 18:54 UTC, ronimizy requested changes
Убрать лишнее наследование в авторизации

2021-09-04 18:54 UTC, ronimizy commented on Source/SeaInk.Core/TableGeneration/ColumnConfigurations/ColumnConfigurationBase.cs
>          /// <param name="start"></param>
Разбей док на комменты к параметрам

2021-09-04 18:54 UTC, ronimizy commented on Source/SeaInk.Core/TableGeneration/TableConfigurations/DefaultTableConfiguration.cs
> +        public SheetIndex Draw(Sheet sheet, SheetIndex start)
same

2021-09-04 19:17 UTC, ronimizy commented on Source/SeaInk.Core/TableGeneration/Authorisation.cs
> +            var findFiles = await driveService.FindFilesAsync(listActionConfiguration);
имя искомой папки стоит передавать аргументом функции

2021-09-04 19:20 UTC, ronimizy submitted a review, later dismissed

2021-09-05 07:07 UTC, FrediKats commented on Source/SeaInk.Core/TableGeneration/Authorisation.cs
> +    public class Authorisation
Кажется, это пишется не так.
А если и так, что это слишком дженерик название, будут колизии.

2021-09-05 08:11 UTC, ronimizy commented
Думаю класс `Authorization` стоит вообще убрать, всё необходимое сделать в `Setup` в тестах. А потом всё это как-то по другому сделаем, прокинем сервисы через DI.

2021-09-05 08:39 UTC, Ar4eR-ValerA commented
> Думаю класс `Authorization` стоит вообще убрать, всё необходимое сделать в `Setup` в тестах. А потом всё это как-то по другому сделаем, прокинем сервисы через DI.

Поддерживаю. Но просто ты говорил декомпозировать это всё дело. А щас получается снова всё верну в одну кучу, но уже внутри тестов)

2021-09-05 08:44 UTC, ronimizy commented
> А щас получается снова всё верну в одну кучу, но уже внутри тестов)

Ну, с декомпозицией как-то не очень вышло, так что пусть будет в куче)

2021-09-05 08:48 UTC, Ar4eR-ValerA commented on Source/SeaInk.Core/TableGeneration/ColumnConfigurations/ListColumnConfiguration.cs
> +        private readonly Func<SheetIndex, SheetIndex, string> _dataFactory;
Что именно подразумивается под интерфейсом здесь?) Немного не догнал

2021-09-05 13:55 UTC, FrediKats approved these changes

2021-09-05 13:58 UTC, ronimizy reviewed
Вот это бы поправить, а так апрув

2021-09-05 13:58 UTC, ronimizy commented on Source/SeaInk.Tests.Core/TableTests.cs
> +        private List<string> _students, _labs;
Кто-то не читал гайд по кодстайлу)

2021-09-05 13:59 UTC, merged