refactor: decompose division
kysect/SeaInk pull request #65
Opened 2021-08-28 22:07 UTC by FrediKats

Внезапно оказалось, что текущая реализация связей немного не работает. Сущность Division должна связывать множество групп в рамках одного предмета. Но это объединение не учебных групп. В системе явно не хватало сущности StudyGroupSubject - это как раз то, что описывает, что у определённой группы есть определённый предмет (и множество преподавателей). Это и есть единица, которую можно объединять в Division.
Это первый шаг к #38

2021-08-28 23:16 UTC, ronimizy reviewed
Выглядит интересно, завтра с компа гляну подробнее

2021-08-28 23:16 UTC, ronimizy commented on Source/SeaInk.Core/Entities/Mentor.cs
> +    public class Mentor : User
Осуждаю

2021-08-29 07:47 UTC, FrediKats commented on Source/SeaInk.Core/Entities/Mentor.cs
> +    public class Mentor : User
Тыкни любой класс в доке мс, там стоит пробел перед `:`.

https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.creditcardattribute?view=net-5.0

2021-08-29 12:32 UTC, FrediKats commented
close #67 
Оказалось, что падает на добавлении ментора, но проблема с SGS. Видимо, проиграл в захватывание переменной.

2021-08-29 23:21 UTC, ronimizy requested changes
@FrediKats, а ERD перерисуешь? 😁

2021-08-29 23:21 UTC, ronimizy commented on Source/SeaInk.Infrastructure/APIs/ITestUniversitySystemApi.cs
> -        int GetDivisionCallCount { get; }
Всё таки бы штуку с количеством вызовов поддержать

2021-08-29 23:21 UTC, ronimizy commented on Source/SeaInk.Infrastructure/APIs/FakeUniversitySystemApi.cs
> +        //TODO: rework implementation
Тут тоже бы поддержать, метод простой довольно

2021-08-29 23:21 UTC, ronimizy commented on Source/SeaInk.Infrastructure/APIs/FakeUniversitySystemApi.cs
> +        }
это вообще не так должно делаться, нужно создать отдельное поле для фейкера StudyGroupSubject и обращаться к нему в лямбде этого фейкера

2021-08-29 23:21 UTC, ronimizy commented on Source/SeaInk.Infrastructure/APIs/FakeUniversitySystemApi.cs
> -        private int _getDivisionCallCount;
не помешает поддержка

2021-09-12 10:58 UTC, FrediKats commented on Source/SeaInk.Infrastructure/APIs/ITestUniversitySystemApi.cs
> -        int GetDivisionCallCount { get; }
А зачем? 🤔

2021-09-12 11:25 UTC, FrediKats commented
Вернул обратно Division и изменения. Вынес фейкер.

2021-09-12 11:40 UTC, ronimizy commented on Source/SeaInk.Infrastructure/APIs/FakeUniversitySystemApi.cs
> +        private readonly Faker<StudyGroupSubject> _studyGroupFaker;
Так как у нас есть сущность `StudyGroup` лучше переименовать этот фейкер в `_studyGroupSubjectFaker`

2021-09-12 12:46 UTC, ronimizy requested changes
Если считаешь что штука с количеством вызовов не нужна, то можешь её выпилить вместе с `ITestUniversitySystemApi`

2021-09-12 12:46 UTC, ronimizy commented on Source/SeaInk.Endpoints.Shared/Dto/StudyGroupSubjectDto.cs
> +    }
```suggestion
    public record StudyGroupSubjectDto(
        int Id,
        StudyGroupDto StudyGroup,
        SubjectDto Subject,
        List<int> MentorIds);
```

2021-09-12 12:46 UTC, ronimizy commented on Source/SeaInk.Infrastructure/APIs/FakeUniversitySystemApi.cs
> +                    Id = ++faker.IndexFaker,
В доке к индекс фейкеру сказано что он автоинкрементится. Id - это в нашей бд, а тут нужно генерить UniversityId, если не сложно будет, то переделай пж другие индексы тоже на это, а то я когда делал не прошарил про такую фичу

2021-09-12 13:48 UTC, FrediKats commented on Source/SeaInk.Infrastructure/APIs/FakeUniversitySystemApi.cs
> +                    Id = ++faker.IndexFaker,
Не очень понял, что переделывать. Мы генерируем _какие-то_ id. Они точно не будут мапиться на реальные, они бай дизайн фейковые. И разницы между 222345 и 345 нет никакой.

2021-09-12 18:27 UTC, ronimizy commented on Source/SeaInk.Infrastructure/APIs/FakeUniversitySystemApi.cs
> +                    Id = ++faker.IndexFaker,
1. Инкрементить самому айпишник не надо, так как это делается `IndexFaker`'ом
2. Ты тут генеришь `Id` - айди в нашей базе данных, АПИ университета никак не может сгенерить этот айди. Он должен генерить `UniversityId` - айди в системе университета.
3. У меня "текущие айдишники" держатся отдельными полями, но так как в фейкере есть функция авто генерации айдишников, то стоит на неё переделать, так как это чище и сделает логику генерации айдишников единообразной

2021-11-22 07:21 UTC, ronimizy approved these changes

2021-11-23 16:37 UTC, merged