Table layout
kysect/SeaInk pull request #72
Opened 2021-11-27 14:37 UTC by ronimizy

Closes #9

2021-11-29 12:37 UTC, annchous reviewed
Короче, пусть дальше @hrrrrustic cмотрит

2021-11-29 12:37 UTC, annchous commented on Source/SeaInk.Application/TableLayout/Models/TableModel.cs
> +    }
Не знаю, как там бай-дизайн, но названия какого-то или иного идентификатора у этой штуки не должно быть?

2021-11-29 12:37 UTC, annchous commented on Source/SeaInk.Application/TableLayout/Models/StudentModel.cs
> +    }
Аналогичный вопрос про идентификатор.

2021-11-29 12:37 UTC, annchous commented on Source/SeaInk.Application/TableLayout/Models/AssignmentModel.cs
> +        public bool? IsMilestone { get; private init; }
А почему наллабл?

2021-11-29 12:37 UTC, annchous commented on Source/SeaInk.Application/SeaInk.Application.csproj
> +    </ItemGroup>
Вот это

2021-11-29 12:37 UTC, annchous commented on Source/SeaInk.Application/SeaInk.Application.csproj
> +    </ItemGroup>
Что?

2021-11-29 12:37 UTC, annchous commented on Source/SeaInk.Application/TableLayout/Components/AssignmentColumnComponent.cs
> +                                                      IValueSettingLayoutComponent<AssignmentProgress>
Какое-то катастрофическое количество интерфейсов, надеюсь, что во всём виноват interface segregation)

2021-11-29 12:39 UTC, hrrrrustic commented
А я тут причем вообще...

2021-11-29 12:45 UTC, hrrrrustic reviewed
Я ничего не понял. ООП порнухи больше чем смысловой нагрузки кода

2021-11-29 12:45 UTC, hrrrrustic commented on Source/SeaInk.Application/Exceptions/CrossedFrameException.cs
> +        protected CrossedFrameException(SerializationInfo info, StreamingContext context)
удалить

2021-11-29 12:45 UTC, hrrrrustic commented on Source/SeaInk.Application/Exceptions/CrossedFrameException.cs
> +    [Serializable]
удалить

2021-11-29 12:45 UTC, hrrrrustic commented on Source/SeaInk.Application/Exceptions/InvalidScaleComponentException.cs
> +        protected InvalidScaleComponentException(SerializationInfo info, StreamingContext context)
удалить

2021-11-29 12:45 UTC, hrrrrustic commented on Source/SeaInk.Application/Exceptions/InvalidScaleComponentException.cs
> +    [Serializable]
удалить

2021-11-29 12:45 UTC, hrrrrustic commented on Source/SeaInk.Application/Exceptions/MissingAssignmentComponentException.cs
> +    [Serializable]
надоело

2021-11-29 12:45 UTC, hrrrrustic commented on Source/SeaInk.Application/TableLayout/CommandInterfaces/IValueGettingLayoutComponent.cs
> +    public interface IValueGettingLayoutComponent<out T>
в чем суть ковариантности тут?

2021-11-29 12:45 UTC, hrrrrustic commented on Source/SeaInk.Application/TableLayout/Commands/AggregateValuesCommand.cs
> +            _provider = provider.ThrowIfNull(nameof(provider));
копипастни с 6 нета этот метод, чтобы не делать неймоф

2021-11-29 12:45 UTC, hrrrrustic commented on Source/SeaInk.Application/TableLayout/Components/LabelComponent.cs
> +            => editor.EnqueueWrite(begin, new[] { new[] { _value } });
что?

2021-11-29 13:14 UTC, ronimizy commented on Source/SeaInk.Application/TableLayout/Components/AssignmentColumnComponent.cs
> +                                                      IValueSettingLayoutComponent<AssignmentProgress>
Он самый

2021-11-29 13:15 UTC, ronimizy commented on Source/SeaInk.Application/Exceptions/CrossedFrameException.cs
> +        protected CrossedFrameException(SerializationInfo info, StreamingContext context)
Sonarcloud ругается при отсутствии этого

2021-11-29 13:15 UTC, ronimizy commented on Source/SeaInk.Application/Exceptions/CrossedFrameException.cs
> +    [Serializable]
Sonarcloud ругается при отсутствии этого

2021-11-29 13:15 UTC, ronimizy commented on Source/SeaInk.Application/Exceptions/InvalidScaleComponentException.cs
> +        protected InvalidScaleComponentException(SerializationInfo info, StreamingContext context)
Sonarcloud ругается при отсутствии этого

2021-11-29 13:16 UTC, ronimizy commented on Source/SeaInk.Application/Exceptions/InvalidScaleComponentException.cs
> +    [Serializable]
Sonarcloud ругается при отсутствии этого

2021-11-29 13:16 UTC, ronimizy commented on Source/SeaInk.Application/Exceptions/MissingAssignmentComponentException.cs
> +    [Serializable]
Sonarcloud ругается при отсутствии этого

2021-11-29 13:18 UTC, ronimizy commented on Source/SeaInk.Application/TableLayout/Models/TableModel.cs
> +    }
Это модель которая держит данные получаемые из таблицы и устанавливаемые в него, из таблицы айди не получить, и в таблицу его совать не надо, так что смысла в нём нет.

2021-11-29 13:18 UTC, ronimizy commented on Source/SeaInk.Application/TableLayout/Models/StudentModel.cs
> +    }
Это модель которая держит данные получаемые из таблицы и устанавливаемые в него, из таблицы айди не получить, и в таблицу его совать не надо, так что смысла в нём нет.

2021-11-29 13:19 UTC, ronimizy commented on Source/SeaInk.Application/TableLayout/Models/AssignmentModel.cs
> +        public bool? IsMilestone { get; private init; }
Назначение этого описал выше. Единственное что обязательно должно быть в таблице у assignment это название, остальные параметры могут отсутствовать

2021-11-29 13:20 UTC, ronimizy commented on Source/SeaInk.Application/SeaInk.Application.csproj
> +    </ItemGroup>
ну это я скопировал с лаб

2021-11-29 13:20 UTC, ronimizy commented on Source/SeaInk.Application/SeaInk.Application.csproj
> +    </ItemGroup>
чтобы работал стайлкоп

2021-11-29 13:27 UTC, ronimizy commented on Source/SeaInk.Application/TableLayout/CommandInterfaces/IValueGettingLayoutComponent.cs
> +    public interface IValueGettingLayoutComponent<out T>
ну на всякий

2021-11-29 13:33 UTC, FrediKats commented on Source/SeaInk.Application/TableLayout/CommandInterfaces/IValueGettingLayoutComponent.cs
> +    public interface IValueGettingLayoutComponent<out T>
Перепиши на всякий случай.

2021-11-29 13:34 UTC, FrediKats commented on Source/SeaInk.Application/Exceptions/MissingAssignmentComponentException.cs
> +    [Serializable]
Ты бы уже мог поменять конфиг сонара.....................................................................................................................................................................................................................................................

2021-11-29 16:50 UTC, hrrrrustic commented on Source/SeaInk.Application/Exceptions/CrossedFrameException.cs
> +    [Serializable]
@FrediKats выруби свой олд режим в сонаре

2021-11-29 16:51 UTC, ronimizy commented on Source/SeaInk.Application/Exceptions/CrossedFrameException.cs
> +    [Serializable]
Пажилая сериализация

2021-12-01 17:27 UTC, Bibletoon requested changes
Жёстко надристал полный пр TryExecute, может посмотреть в сторону FluentValidation?

2021-12-01 17:27 UTC, Bibletoon commented on Source/SeaInk.Application/TableLayout/Indices/ITableIndex.cs
> +        void MoveHorizontally(int i = 1);
Почему i?

2021-12-01 17:32 UTC, ronimizy commented on Source/SeaInk.Application/TableLayout/Components/PlainAssignmentColumnComponent.cs
> +            => Value.GetHashCode();;
кекс

2021-12-01 17:41 UTC, ronimizy commented on Source/SeaInk.Application/TableLayout/Commands/AggregateValuesCommand.cs
> +            return false;
Фактически команда возвращает `true`, если она закончила своё выполнение, так что, команды, которые должны совершить обход по всему дереву компоновщика, по сути не завершаются никогда :/

2021-12-01 17:54 UTC, ronimizy commented on Source/SeaInk.Application/TableLayout/CommandInterfaces/IReducibleLayoutComponent.cs
> +        bool TryRemoveComponent(TComponent component, IScaledTableIndex begin, ITableEditor editor);
Expandable (расширяемый) -> Add component
Reducible (уменьшаемый) -> Remove component

Если такой нейминг кажется плохим, хоть он и корректен в плане инглиша, могу предложить поменять имя интерфейса на IShrinkableLayoutComponent

2021-12-01 17:58 UTC, ronimizy commented on Source/SeaInk.Application/Exceptions/MissingStudentComponentException.cs
> +    [Serializable]
<img width="241" alt="Снимок экрана 2021-12-01 в 20 57 57" src="https://user-images.githubusercontent.com/71693183/144288010-b61b1997-9cc8-4e2c-a7a5-3642730e37c0.png">

2021-12-01 18:04 UTC, Bibletoon commented on Source/SeaInk.Application/TableLayout/CommandInterfaces/IReducibleLayoutComponent.cs
> +        bool TryRemoveComponent(TComponent component, IScaledTableIndex begin, ITableEditor editor);
Думаю что Reducible и Shrinkable эквивалентны, так что особой разницы нет (хотя второе мне импонирует больше)
Может стоит подумать и как-то обозначить то, что убираем именно child компонент

2021-12-01 18:04 UTC, ronimizy commented on Source/SeaInk.Application/TableLayout/Components/LabelComponent.cs
> +            => editor.EnqueueWrite(begin, new[] { new[] { _value } });
Запись сетки значений начиная с данного индекса

2021-12-01 18:13 UTC, ronimizy commented
@hrrrrustic @FrediKats 
https://github.com/kysect/SeaInk/pull/72#discussion_r758326325

Как ругается то, прям аж Major)
<img width="571" alt="Снимок экрана 2021-12-01 в 21 12 21" src="https://user-images.githubusercontent.com/71693183/144290171-a009a9dd-e14e-4234-98e5-ad79025d659f.png">

2021-12-03 21:27 UTC, hrrrrustic commented
оаоаооа ммм натягивание фарш штук на сишарп
Как я и говорил еще года полтора назад в какой-то другой репе Егору - выглядит максимально уродски и непонятно зачем

2021-12-04 06:33 UTC, Bibletoon approved these changes
Поправь только перед тем как мерджить

2021-12-04 06:33 UTC, Bibletoon commented on Source/SeaInk.Sample/TableLayoutSample.cs
> +            var provider = (ITableDataProvider)new object();
InvalidCast

2021-12-04 06:33 UTC, Bibletoon commented on Source/SeaInk.Sample/SeaInk.Sample.csproj
> +
Вообще не понял прикол делать Sample ClassLibrary, а не ConsoleApplication

2021-12-04 07:23 UTC, merged