Endpoints
kysect/SeaInk pull request #78
Opened 2021-12-16 20:55 UTC by ronimizy

На данный момент создание табличек не работает, так как нужно настроить стерилизацию лейаутов.
Так же мне кажется что не стоит хранить в базе данных отдельные компоненты (кринге с тем, что у лейаут компонента есть найди, да и это не особо нужно), а просто запихнуть в `StudyGroupSubjectLayout` строку с лейяутом в стерилизованном виде, @FrediKats your thoughts?

2021-12-17 14:12 UTC, I-SER-I commented on Source/SeaInk.Infrastructure/SeaInk.Infrastructure.DataAccess/Extensions/DbSetExtensions.cs
> +            Type t = typeof(T);
Звучит

2021-12-17 14:22 UTC, I-SER-I commented on Source/SeaInk.Infrastructure/SeaInk.Infrastructure.DataAccess/Extensions/DbSetExtensions.cs
> +        public static void AddOrUpdate<T>(this DbSet<T> dbSet, T data)
А чем нам этот товарищ не угодил?)
https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.migrations.idbsetextensions.addorupdate?view=entity-framework-5.0.0

2021-12-17 14:28 UTC, ronimizy commented on Source/SeaInk.Infrastructure/SeaInk.Infrastructure.DataAccess/Extensions/DbSetExtensions.cs
> +        public static void AddOrUpdate<T>(this DbSet<T> dbSet, T data)
<img width="283" alt="Screenshot 2021-12-17 at 17 27 55" src="https://user-images.githubusercontent.com/71693183/146559269-c84490b3-9804-413a-b23d-7767e26a19da.png">

2021-12-17 14:51 UTC, I-SER-I commented on Source/SeaInk.Infrastructure/SeaInk.Infrastructure.DataAccess/Extensions/DbSetExtensions.cs
> +        public static void AddOrUpdate<T>(this DbSet<T> dbSet, T data)
ок
https://github.com/dotnet/efcore/issues/4526

2021-12-18 08:45 UTC, FrediKats commented
Ну... Запихни строку, хз что сказать)

2021-12-18 08:56 UTC, FrediKats requested changes

2021-12-18 08:56 UTC, FrediKats commented on Source/SeaInk.Application/Commands/ApplyStudyStudentGroupTableDifference.cs
> +public static class ApplyStudyStudentGroupTableDifference
А почему StudyStudent? Что э Что это значит?

2021-12-18 08:56 UTC, FrediKats commented on Source/SeaInk.Application/Commands/ApplyStudyStudentGroupTableDifference.cs
> +            return default;
Это же не ок.. Ты вернёшь null.

2021-12-18 08:56 UTC, FrediKats commented on Source/SeaInk.Application/Commands/CalculateStudyStudentGroupTableDifference.cs
> +                .FindAsync(new object[] { request.StudyStudentGroupId }, cancellationToken)
Выглядит очень усложно. НАм вообще нужно поддерживать отмену? Мне кажется, что нет. Если это из-за тоого, что решарпер так сказал, то давайте рулы поправим.

2021-12-18 08:56 UTC, FrediKats commented on Source/SeaInk.Application/Commands/CreateStudyStudentGroupTable.cs
> +                return response;
Тут какая-то логика появляется. Почему она в команде, а не в доменном проекте с доменом?

2021-12-18 08:56 UTC, FrediKats commented on Source/SeaInk.Application/Commands/RegisterMentor.cs
> +                studyGroups.ToList().ForEach(ssg => ssg.AddMentors(mentor));
Написал бы уже свой экстеншен метод для ForEach/

2021-12-18 08:56 UTC, FrediKats commented on Source/SeaInk.Application/Commands/UpdateMentor.cs
> +                    .GetMentorSubjectGroupsAsync(mentor, subject, cancellationToken)
Вызываем GetMentorSubjectGroup, а получаем StudentGroupUniversity. Очень много вопросов.

2021-12-18 08:56 UTC, FrediKats commented on Source/SeaInk.Application/Dtos/StudyAssignmentDto.cs
> +namespace SeaInk.Application.Dtos
Почему у тебя проект с Dto зависит от Entities.Это должен быть проект с около 0 зависимостей, чтобы его можно было легко портировать.

2021-12-18 08:56 UTC, FrediKats commented on Source/SeaInk.Application/Extensions/ServiceCollectionExtensions.cs
> +            services.BuildServiceProvider().GetRequiredService<IIdentityService>().GetCurrentMentor().GetAwaiter().GetResult();
Что? Почему?

2021-12-18 09:00 UTC, FrediKats commented on Source/SeaInk.Infrastructure/SeaInk.Infrastructure.Integrations/Class1.cs
> +public class Class1 { }
Ладно.

2021-12-18 09:01 UTC, ronimizy commented on Source/SeaInk.Application/Commands/ApplyStudyStudentGroupTableDifference.cs
> +            return default;
<img width="400" alt="Screenshot 2021-12-18 at 12 01 39" src="https://user-images.githubusercontent.com/71693183/146635711-065ed200-2e4d-40f1-8b75-66f81d5a538c.png">

2021-12-18 09:02 UTC, ronimizy commented on Source/SeaInk.Application/Commands/ApplyStudyStudentGroupTableDifference.cs
> +public static class ApplyStudyStudentGroupTableDifference
Study StudentGroup

2021-12-18 09:06 UTC, ronimizy commented on Source/SeaInk.Application/Commands/CalculateStudyStudentGroupTableDifference.cs
> +                .FindAsync(new object[] { request.StudyStudentGroupId }, cancellationToken)
Не, это после того как TAP почитал)

2021-12-18 17:34 UTC, FrediKats approved these changes
Если что, я только первые пару файлов посмотреть успел ( Надеюсь, ревью хоть как-то помогло.

2021-12-18 17:36 UTC, FrediKats commented
О, мне Анчоус напомнила. Супер сильно осуждаю за "Не пугайтесь огромного диффа". Ты каждый раз так делаешь, я каждый раз говорю, что это ультраплохо, ты продолжаешь так делать =\

2021-12-19 19:32 UTC, I-SER-I commented on Source/SeaInk.Infrastructure/SeaInk.Infrastructure.Integrations/GoogleSheets/GoogleSheetsTableEditor.cs
>      public class GoogleSheetsTableEditor : ITableEditor
```suggestion
    public class GoogleSheetsTableEditor : ISheetsTableEditor
```
Т.к у нас GoogleSheetsService : ISheetsService

2021-12-24 12:58 UTC, merged